### ISSUE TITLE
kyma provision gardener uses old image

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/cli#1067]
**Description**
When creating a kyma cluster with latest from main by using `kyma provision gardener gcp ....` we get this error bellow.
![image](https://user-images.githubusercontent.com/478866/140004555-0a1878d6-a3e3-4867-bfd1-c47c0ba09144.png)

**Expected result**
We should use the latest gardener image

**Actual result**

We use a deprecated one.

**Steps to reproduce**

Produce any cluster with `kyma provision gardener ....` and see the error in the gardener interface

**Troubleshooting**

**Comment by rakesh-garimella** [comment]
The garden linux images have been updated
