### ISSUE TITLE
checksum mismatch for kyma-cli 1.24.7

### ISSUE THREAD

**Issue by chenrui333** [kyma-project/cli#1075]
👋  homebrew-core is trying to bottle the formulae for macOS Monterey release, and we found that `kyma-cli 1.24.7` got retagged and caused the checksum mismatch. Right now I am raising this issue to see if we do need to change the formula artifact (if there is no function change, we dont have to re-release the formula). Let me know if that makes sense.

- relates to https://github.com/Homebrew/homebrew-core/pull/88858

**Comment by rakesh-garimella** [comment]
While releasing the kyma cli with version 1.24.7 we had some hiccups and had to push a new [commit](https://github.com/kyma-project/cli/pull/1058) to make the release. This would have caused the retagging of release and thats why there is a checksum mismatch. The PR looks fine to me.

**Comment by chenrui333** [comment]
I see, thanks for confirming it!
