### ISSUE TITLE
"fatal error: concurrent map read and map write" Panic while installing CRDs component

### ISSUE THREAD

**Issue by dbadura** [kyma-project/cli#1120]
**Description**
While installing CRDs on prow job, the cli panic with error: `fatal error: concurrent map read and map write`

**Expected result**

CLI shouldn't panic

**Steps to reproduce**

It crashed on `pre-main-kyma-serverless-k3d-integration`

More detialed logs is here: [k3d-install-cli-crash.txt](https://github.com/kyma-project/cli/files/7683232/k3d-install-cli-crash.txt)

**Troubleshooting**

**Comment by skhalash** [comment]
Not reproducible anymore.
