### ISSUE TITLE
Kyma provision k3d requires root

### ISSUE THREAD

**Issue by dbadura** [kyma-project/cli#1128]
**Description**
When I want to provision k3d cluster, the cli require root priviledges.

**Actual result**
Root is required, because provision by default try to use ports 80 and 433

**Steps to reproduce**

Run on Linux as normal user:
```
kyma provision k3d
```

**Troubleshooting**

I run the following command to mitigate this issue:
```
kyma provision k3d -p 8080:8080@loadbalancer -p 8433:8433@loadbalancer
```

**Comment by a-thaler** [comment]
We are aware of the situation and already improved the error message to outline the alternative of using a custom port more prominent. We decided to go with that solution as it feels more convenient to not remember a specific port number to be used later in the local URLs for exposed APIs. So either you accept the port 80 solution by granting permissions or you select a port of your choice which you can remember.

What is your expected result?

**Comment by dbadura** [comment]
Do you know what has changed?
I noticed that cli in version: `Kyma CLI version: stable-267-g2cf690f` and latest `main` works without problem.

The message is ok.
Is `kyma provision k3d` command used only for local development? If yes, the cli shouldn't try bind privileged ports.

**Comment by a-thaler** [comment]
As I outlined we improved the error message, furthermore we added a troubleshooting guide now.
K3D is used only for local development. I agree that in theory it should not use reserved ports, however the convenience on mac and win is really good, having the improved message I think we are fine for now.
