### ISSUE TITLE
Support Dry-Run for Kyma reconciliation

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/cli#1135]
**Description**

Customers should be able to execute a reconciliation run in a Dry-Run mode. Goal is to get an overview of the resources which would be modified.

Depends on https://github.com/kyma-incubator/reconciler/issues/654

AC:
* CLI support Dry-run flag
* Setting the dry-run will trigger a reconciliation which does not modify the resources on the cluster but shows an overview of the changes it would apply

**Reasons**

Enable users to see up-front the changes of a reconciliation run. Related to https://github.com/kyma-project/kyma/issues/12960

**Attachments**

**Comment by a-thaler** [comment]
Please improve the command flag description. It must be clearly stated that the generated resources are not enough to apply kyma using kubectl. So document what resources it covers and mark it as an alpha feature
Current description is: Render manifests only.

**Comment by a-thaler** [comment]
Feedback will be covered in https://github.com/kyma-project/kyma/issues/13297
