### ISSUE TITLE
Timeout on kyma deploy does not indicate the hanging component

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/cli#1138]
**Description**
When deploying kyma and a component is hanging, there is no indication on which component was hanging.

```
./bin/kyma-darwin deploy -s 2.0.1 -p evaluation
- No previous Kyma version found
- Using Kyma from the workspace directory: /Users/xxx/.kyma/sources
- Installed Prerequisites
...
- Component 'rafter' deployed
- Component 'application-connector' deployed
- Component 'monitoring' deployed
X Timeout reached while waiting for deployment to complete
```

The actual component causing the problem is the "logging" component, all others where installed successful.

Please improve the error message to indicate which component are not installed

**Expected result**
You clearly can identify the failing component so that troubleshooting will be improved.

**Actual result**
No hint on which component caused the timeout.

**Steps to reproduce**

**Troubleshooting**

**Comment by tobiscr** [comment]
@Tomasz-Smelcerz-SAP : afaik this issue is already fixed, right?

**Comment by a-thaler** [comment]
At least you see the list of components which were not installed, good enough
