### ISSUE TITLE
Installing from Kyma branch

### ISSUE THREAD

**Issue by arifC** [kyma-project/cli#116]
**Description**
It would be helpful to have an option like `--branch`. This could mainly be used to install the current master version of Kyma.

**Reasons**
Currently, installing the master branch of Kyma is done by checking out the Kyma sources locally and triggering the installation. It is more convenient if the CLI takes care of checking out the branch and then triggers a local installation based on the the Kyma sources.

**Comment by a-thaler** [comment]
Will be solved by changes introduced in https://github.com/kyma-project/cli/issues/87
