### ISSUE TITLE
Timeout on deploy returns a zero exit code - considered a success.

### ISSUE THREAD

**Issue by Tomasz-Smelcerz-SAP** [kyma-project/cli#1166]
**Description**

When a timeout occurs during `kyma deploy`, the command returns exit code 0, which is, by convention, considered a success.
This breaks the logic in many scripts, for example in pipelines, that report success or failure based on that value.
A non-zero exit code should be returned instead.

**Expected result**

A non-zero exit code should be returned

**Actual result**

exit code with value of 0 (zero) is returned

**Steps to reproduce**

- `kyma provision k3d`
- `kyma deploy --timeout 2m`
- `echo $?`

**Example run log**
```
PROMPT% kyma deploy --timeout 2m
- No previous Kyma version found
- Using Kyma from the workspace directory: /Users/i303773/.kyma/sources
- Installed Prerequisites
- Component 'CRDs' deployed
X Component 'certificates' failed. Retrying...
no matches for kind "Gateway" in version "networking.istio.io/v1alpha3"

- Component 'istio-configuration' deployed
- Component 'certificates' deployed
- Component 'cluster-essentials' deployed
- Component 'service-catalog-addons' deployed
- Component 'cluster-users' deployed
- Component 'serverless' deployed
- Component 'application-connector' deployed
X Timeout reached while waiting for deployment to complete
PROMPT% echo $?
0
```

**Comment by tobiscr** [comment]
Fixed in https://github.com/kyma-project/cli/pull/1167
