### ISSUE TITLE
Add cli to Krew repo

### ISSUE THREAD

**Issue by atakanyenel** [kyma-project/cli#117]
Kubernetes-sigs have a kubectl plugin manager called krew. https://github.com/kubernetes-sigs/krew

We can add kyma-cli to krew index repo, https://github.com/kubernetes-sigs/krew-index, so that people can install cli with the command `kubectl krew install kyma`. It's a yaml file with our released binaries.

**Comment by a-thaler** [comment]
Nice idea. Not sure if integration with 3party-tools is a focus of that manager, but we should have a look indeed.

**Comment by a-thaler** [comment]
I need to close it for now as we will not find time for it and I think the tool is still not popular enough
