### ISSUE TITLE
CLI with flag -s "commit" -w "kyma-repo location" wipes eveything from kyma-repo location

### ISSUE THREAD

**Issue by dbadura** [kyma-project/cli#1173]
**Description**
When you want to deploy kyma from commit, the workspace location is cleaned with ci mode, the workspace directory is wiped.
I don't know why the directory is wiped if CLI create directory with commit ID and then put kyma resources into newly created repository

**Expected result**
Kyma CLI shouldn't wipe the whole directory

**Actual result**
Kyma CLI clean all in workspace directory

**Steps to reproduce**
```
mkdir /tmp/test
touch /tmp/test/README.md
kyma deploy -s a318bcac41c64c4c5f79465ad257378fed17a945 -w /tmp/test --ci
```
**Troubleshooting**

**Comment by dbadura** [comment]
This bug totally remove cache in case of different version installation.

**Comment by tobiscr** [comment]
Will become obsolete when moving to modularised Kyma.

**Comment by tobiscr** [comment]
Closing issue as we are not going to deprecate the command (in favour of modularisation) and not investing further efforts for it
