### ISSUE TITLE
kyma dashboard in Ubuntu on WSl2

### ISSUE THREAD

**Issue by VishnAndr** [kyma-project/cli#1193]
**Description**

When running `kyma dashboard`, it gets the container image and starts it. I can see it running in `docker ps`. And that's the only one. And there is an output after `kyma dashboard` in the terminal.:
```
Status: Downloaded newer image for eu.gcr.io/kyma-project/busola:latest
- Started container: busola
- Opening the Kyma dashboard in the default browser using the following url: http://localhost:3001
```
However, in the browser http://localhost:3001 gets 'ERR_CONNECTION_REFUSED'.

If I stop `kyma dashboard` and run in the same terminal the following command it works just fine:
`docker run --rm -it -p 3001:3001 -e DOCKER_DESKTOP_CLUSTER=true -e NODE_ENV=development --name busola eu.gcr.io/kyma-project/busola:latest
`

Kyma cli 2.0.4 on WSL2 with Docker Desktop.

**Expected result**

`kyma dashboard` should open the busola console on http://localhost:3001

**Actual result**
Getting ERR_CONNECTION_REFUSED in the browser

**Steps to reproduce**

**Troubleshooting**

**Comment by VishnAndr** [comment]
One more thing to add: I tried with -p key for 'kyma dashboard' command with different ports. The same result.

**Comment by a-thaler** [comment]
I can reproduce it as well. Using your docker statement with an additional `--network=host` reveals same symptoms. Without it all works good. This flag is set for linux in the CLI, see https://github.com/kyma-project/cli/pull/1133.

**Comment by dennis-ge** [comment]
Hey @VishnAndr, the issue should be fixed now. You can verify it with the new [stable version](https://github.com/kyma-project/cli#kyma-cli-binaries) of the CLI. If something doesn't work, please let us know.
