### ISSUE TITLE
Improve the JSON schema definition

### ISSUE THREAD

**Issue by pPrecel** [kyma-project/cli#1209]
**Description**

JSON schema which is a part of [this story](https://github.com/kyma-project/cli/issues/576) is as simple as possible and now is a time to add other features:
- vscode should suggest which fields are required by which story (inline function or git function)
- ...

**Reasons**

Make JSON schema as useful as possible

**Comment by kwiatekus** [comment]
Lets add this after releasing stable v1 version

**Comment by kwiatekus** [comment]
So far noone was complaining about missing autocompletion..
Closing.
