### ISSUE TITLE
Support for the IntelliJ IDE regarding the schema for `config.yaml`

### ISSUE THREAD

**Issue by pPrecel** [kyma-project/cli#1215]
**Description**

[This story](https://github.com/kyma-project/cli/issues/576) provided changes to generate schema for the `config.yaml` file. Now it's time to support more IDEs than VScode only and the next supported one should be one of the most popular IntelliJ IDE.

**Reasons**

Add possibility to work on the function's workspaces much easier using IntelliJ IDE.

**Comment by kwiatekus** [comment]
Still valid but low prio

**Comment by kwiatekus** [comment]
Noone requested it so far. Closing due to very low priority
