### ISSUE TITLE
Autocompletion for zsh prints out data

### ISSUE THREAD

**Issue by Halamix2** [kyma-project/cli#1245]
**Description**

Autocompletion for zsh prints out to stderror

**Expected result**

No data is outputted to the console

**Actual result**

The command returns `{"level":"INFO","time":"2022-04-19T09:40:03.718+0200","message":"Initializing component reconciler 'busola-migrator'"}` in stderr

**Steps to reproduce**

run `source <(kyma completion zsh)`

**Troubleshooting**

Kyma CLI version: 2.1.3

**Comment by clebs** [comment]
Hi @Halamix2,
this issue has already been solved and it will be fixed in the next release.
