### ISSUE TITLE
Determine concurrency at runtime

### ISSUE THREAD

**Issue by clebs** [kyma-project/cli#1284]
**Description**

Whenever possible, determine the best fitting concurrency (# of workers) at runtime by using `runtime.NumCPU()`.

The priority order to set the concurrency would be:
1. User provided `--concurrency` flag
2. Number of cores determined at runtime.
3. If number of cores is unknown set to default of 4.

**Reasons**

Better resource utilisation in any scenario and hardware.

**Comment by tobiscr** [comment]
@clebs ; is this flag still supported when moving to the new `deploy` command?

**Comment by clebs** [comment]
Hi @tobiscr, that is a very good point. With the new deploy I do not think this is relevant anymore. Closing the issue.
