### ISSUE TITLE
CI/CD: Create Gardener test-clusters via Kyma CLI instead calling Gardner directly and passing Shoot-Spec

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/cli#1287]
**Description**

Some pipelines are creating Gardener test clusters by sending a [Shoot-Spec](https://github.com/kyma-project/test-infra/blob/main/prow/scripts/resources/reconciler/shoot-template.yaml) to the Gardener API. This has the drawback that the spec needs to be regularly updated when Gardener changes their API rules (e.g. removing support for particular VM images etc.). To avoid such efforts in the longterm, the [Kyma CLI should be used to provision Gardener clusters](https://github.com/kyma-project/cli/blob/main/docs/gen-docs/kyma_provision_gardener.md) instead calling the Gardener API directly.

AC:
* Instead calling the Gardner API and sending a Shoot-Spec, the [Kyma CLI](https://github.com/kyma-project/cli/blob/main/docs/gen-docs/kyma_provision_gardener.md) is used to provision a test cluster in Gardener
* [Shoot-Spec](https://github.com/kyma-project/test-infra/blob/main/prow/scripts/resources/reconciler/shoot-template.yaml) is dropped from the test-infra repository

**Reasons**

Use Kyma CLI for Gardener interaction to avoid maintenance efforts for Gardener Shoot Spec.

**Attachments**

**Comment by tobiscr** [comment]
Only valid for old reconciler pipelines!

**Comment by janmedrek** [comment]
Since we are dropping the support for the old reconciler I am closing this issue. Cheers!
