### ISSUE TITLE
Unsupported warning for ARM Macs

### ISSUE THREAD

**Issue by clebs** [kyma-project/cli#1292]
**Description**

ARM Macs are not fully supported at the moment for Kyma deployment. For this reason we need to show a clear warning to the user when using the CLI on an ARM Mac.

Use has to be asked whether he want to continue with the installation of abort it.

Wording: `Mac M1 architecture is currently not supported by Kyma and the deployment can fail. Do you want to proceed?`

AC:
* A message is shown when an ARM architecture is detected
* User has the option to decide to either continue with the deployment or to stop.
* If the application failed to detect the OS architecture, the warning will also be shown but without asking the user whether he want to proceed (it will continue automatically)

**Reasons**

Warn users of possible errors when using kyma with new macs until they are fully supported

**Comment by NHingerl** [comment]
Actually I think your draft is pretty good already.
If anything, we could make it shorter:

Original:
`Mac M1 architecture is currently not supported by Kyma and the deployment can fail. Do you want to proceed?`
Shorter:
`Kyma deployment on Mac M1 might fail. Do you want to proceed anyway?`

**Comment by NHingerl** [comment]
What's the purpose of this ticket? 
In June, Borja said the warning text was used. Shouldn't that implementation have closed the issue?
