### ISSUE TITLE
Kyma 2.3.0 installation fails on random components with context deadline exceeded

### ISSUE THREAD

**Issue by franpog859** [kyma-project/cli#1298]
**Description**

Kyma installation fails on k3d. I use k3d in version v5.4.1, k3s in version v1.22.7-k3s1 (default), kyma-cli in version: 2.3.0 and MacOC in version 12.4

**Expected result**

The tutorial from [the official documentation works](https://kyma-project.io/docs/kyma/latest/02-get-started/01-quick-install/#install-kyma) and Kyma is properly installed on the k3d cluster

**Actual result**

Installation fails on ory and rafter:
```
➜  kyma git:(main) kyma provision k3d
  Checking if port flags are valid
  Checking if k3d registry of previous kyma installation exists
  Checking if k3d cluster of previous kyma installation exists
  Deleted k3d registry of previous kyma installation
- k3d status verified
- Created k3d registry 'kyma-registry:5001'
- Created k3d cluster 'kyma'

➜  kyma git:(main) kyma deploy
- No previous Kyma version found
- Using Kyma from the workspace directory: /Users/i354518/.kyma/sources/2.3.0
- Initial setup
- Component 'CRDs' deployed
- Component 'certificates' deployed
- Component 'cluster-essentials' deployed
- Component 'istio' deployed
- Component 'logging' deployed
- Component 'eventing' deployed
X Component 'ory' failed
context deadline exceeded

X Component 'rafter' failed
context deadline exceeded

X Deploying Kyma

Deployed Components: 6/8
Could not deploy the following components:
- ory
- rafter

Error: kyma deployment failed

➜  kyma git:(main) k3d version
k3d version v5.4.1
k3s version v1.22.7-k3s1 (default)
```
Sometimes it fails also on serverless, service-catalog-addons, logging, application-connector, monitoring or anything to be honest probably

**Steps to reproduce**

Install all the tools in the provided versions, run `kyma provision k3d`, and then `kyma deploy`

**Comment by tobiscr** [comment]
As we are on Kyma 2.6 already and we recommend to upgrade regularly, I would close this ticket as obsolete. Please re-open it if the issue has still relevance.
