### ISSUE TITLE
Command: verify module

### ISSUE THREAD

**Issue by clebs** [kyma-project/cli#1303]
**Description**

Kyma modules are released and distributed as OCI container images following the [OCM](https://github.com/gardener/component-spec) format. This format supports cryptographically signing the images, which will make sure that kyma modules are correct and distributed by a trusted authority.

To help integrate the validation process into different systems (KCP, CI/CD, etc...) the CLI needs to provide a command to verify the authenticity of a module.

**Reasons**

Kyma modules have to be verifiable.

**Attachments**

Implementation should be based on:
https://github.com/gardener/component-cli

**Comment by tobiscr** [comment]
@clebs : can we close this one as we are not using CNUDIE for our Kyma modules?

**Comment by clebs** [comment]
Hi @tobiscr, we are not using CNUDIE but OCM (its successor). I updated the description to make it clear.

The task is still relevant.
