### ISSUE TITLE
Customer gets notified about new Kyma CLI version

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/cli#1312]
**Description**

The Kyma CLI has to inform customers about new CLI releases. He gets informed by showing a notification message on the console output (message is shown before any command output is printed).

AC:
* When the CLi is called, it checks for a new version and notifies the customer about it (info-message at the beginning of the console output)
* Customer can suppress the version-check by setting an additional flag (e.g.  `--no-version-check`)

**Reasons**
Hold customers up-to-date and to ensure they are using latest patched Kyma CLI version.

**Attachments**

**Comment by a-thaler** [comment]
If the request for the version check is failing, the actual command should not fail. Also there should be not a big delay introduced by that.

**Comment by janmedrek** [comment]
Idea: provide some sort of temp file that would limit the number of lines that are being printed. This could lead to i.e. displaying the upgrade notification the first time CLI is used on a given day.

The `--no-version-check` flag functionality can be included in the `-ci` flag that we already have.
