### ISSUE TITLE
Telemetry: measure user behaviour when using Kyma CLI

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/cli#1313]
**Description**

We have to gain more information how customers are using the KYma CLI to get a better understanding how the CLI is primarily used. For measuring the user behaviour, a simple telemetry feature is required.

When the Kyma CLI gets installed, the customer will be asked once whether we want to transfer his user behaviour to a central Kyma CLI telemetry service.

AC:
* Customer has the option to decide whether we wants to participate in the telemetry measuring or not. He has to make this decision just once and it's stored in his local Kyma CLI configuration.
    * If `non-interactive` mode is chosen and no persistent configuration for the CLI can be found, the telemetry is per default disabled
* If telemetry is enabled, the CLI has to send a request to a central telemetry service which tracks the kind of command the user was calling. Following information have to me tracked:
    - Timestamp when the command was called
    - CLI version
    - Name of the executed command
    - Name of the used parameter flag
* If the telemetry service has any technical issues or slow response times, the CLI command should not be delayed (calls to telemetry service have to happen completely asynchronously with well defined HTTP- and connection-timeouts)
* No person data have to be tracked (e.g. no IP-address)
* A telemetry service has to be implemented which includes following features
    * Service is public accessible
    * Exposes simple REST API which allows tracking the above mentione data and stores it in a database
    * Stored data have a retention time of 14 days
    * Rate Limiting has to be configured so that max 150 requests per IP address are accepted per day and max 10.000 requests at all per day.

**Reasons**

Gain statistics how the Kyma CLI is used.

**Attachments**

**Comment by a-thaler** [comment]
If there is any problem with the request to the server, the actual command execution should never be influenced, no delay or crash

**Comment by janmedrek** [comment]
We've decided to not implement this feature for now. The effort would be high and I'd say the gains are not worth it at this point.

Perhaps it will be nice to have that in the future when the adoption for the Modularization part is much higher.
