### ISSUE TITLE
Command: init module

### ISSUE THREAD

**Issue by clebs** [kyma-project/cli#1323]
**Description**

To shorten the setup time for creating a new Kyma module, an `init module` command has to be implemented. It will initialise a new empty kyma module at the desired location with the given module name.

The command will generate the following contents inside a folder called <module_name>:
```
my-module/
    charts/          // folder containing a set of charts (each in a subfolder)
    crds/             // folder containing all CRDs required by the module
    operator/      // folder containing the operator needed to manage the module
    profiles/        // folder containing all profile settings
    channels/     // folder containing all channel settings
    config.yaml  // yaml file containing installation configuration for any chart in the module that requires custom helm settings
    default.yaml // yaml file containing the default CR needed to start the module installation.
    README.md // Documentation explaining the module format, how it translates to OCI images and how to develop one (can be mostly empty at the beginning)
```

AC:
* An `init` command scaffolds the default folder structure and generates mandatory files to start the development of a new module

**Reasons**

Lower the entry barrier to kyma module development for the kyma team and contributors.

**Attachments**
Follow up issue for #1317

**Comment by tobiscr** [comment]
Would be awesome to extend this `init` command by these additional functionalities:

* A module-build configuration file is generated to allow customers to specify their build parameters in the file. The definition as CLI parameter should be still possible and has precedence over the values defined in the file.
* Customer can define in which programming language he would like to implement the module and the scaffolding also generates config-files for main-stream build-tool  (e.g. Makefile for Go, build.xml for Java+Maven or gradle.build for Java+Gradle etc.)

**Comment by jakobmoellersap** [comment]
I agree, maybe to get everything in but still document and prioritise properly we should probably consider splitting this task into a high-prio and low-prio one depending on what we MUST implement vs what would be nice to have.

**Comment by clebs** [comment]
Yes, this addition would in any case be a follow up issue and not part of the AC for this issue.

**Comment by tobiscr** [comment]
Agree, having the option to define the module build-parameters in a file as a important thing as it simplifies the module build call heavily. Such file can also be committed and shared with other developers.

The option for extending the scaffolding to support programming languages (eg. integration for build-tools etc.) is a nice thing, but not mandatory for the beginning.

**Comment by clebs** [comment]
Removed the crds, profiles and channels folders from the module layout in the description as per #1335
