### ISSUE TITLE
create module: support external sources

### ISSUE THREAD

**Issue by clebs** [kyma-project/cli#1324]
**Description**

Add support in the `create module` command `--resource/-r` flag to be able to parse external resources as well.

The format `NAME:TYPE@PATH` should now also accept URLs in the `PATH` section and the resource should be managed accordingly based on it:
- If resource contains a path: execute current logic, creating a blob layer and adding it to the descriptor's `resources`.
- If resource contains a URL: Add the resource to the descriptor's `sources` and do not create any layer.

This feature is still in development and there are several considerations to make decisions on. The progress of the concept will be documented here.

**Reasons**

Support external resources on kyma modules like other images, helm charts or github repositories.

**Comment by tobiscr** [comment]
Descoped for now as use-case has first to be confirmed. Also integration with security concept has to be verified.
