### ISSUE TITLE
Command: enable / disable module

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/cli#1328]
**Description**

Customers required an option to enable/disable a Kyma module on their cluster. The Kyma CLI has to offer a command for enabling/disabling Kyma modules for the target cluster.

This is assuming that no synchronisation of ModuleTemplates happens, it will be handled in the future. This one is only about interacting with resources that are available locally in the cluster.

**AC:**
- [ ] Customer can enable a Kyma module on its cluster
- [ ] Enable command returns a name of the (Kyma) resource that was modified
- [ ] Customer can disable a Kyma module on its cluster
- [ ] Commands do not provide any additional prompts or interactive mode for the enable/disable
- [ ] Wait flag introduced to the commands (defaults to no wait)

**Reasons**

Give customers an option to enable or disable a Kyma module on their cluster.

**Comment by jakobmoellersap** [comment]
Validation of Enable/Disable currently blocked as default customisation has Webhooks disabled.

Decision possibilities:

1. Enable Cert Manager by default if CRDs do not exist and thus ensure prerequisite for web hook via flag. Ensures Webhook certs are always served.
2. Use Init Containers with Certs that eventually expire. Not suitable for production but best scenario for Testing and CI/CD
3. Do not use validation capabilities of web hooks in the `kyma alpha deploy` command
4. Use validation by introducing a code dependency of the lifecycle manager APIs in Kyma CLI
5. Use validation by copying code
