### ISSUE TITLE
init module: optional kubebuilder template

### ISSUE THREAD

**Issue by clebs** [kyma-project/cli#1336]
**Description**

Optionally, instead of generating an empty folder structure when calling `kyma alpha init module` users should be able to indicate if they want to scaffold a kubebuilder module as well.

If the `--kubebuilder` flag is provided, the following needs to be done:
- A new operator needs to be created from a template inside the `operators` folder
- A `Makefile` needs to be created on the root of the module that provides targets to build and template the operator properly as well as download the necessary tools (e.g. kustmoize).
- Clear documentation on the operator template, the `Makefile` and the `README` file on how the kubebuilder setup works.

**Reasons**

**Attachments**

**Comment by jakobmoellersap** [comment]
Can we change the flag to `kubebuilder`? After all we are opinionated on the operator, not the templating engine here right?

**Comment by clebs** [comment]
This issue is no longer relevant, the `init module` command will be removed in https://github.com/kyma-project/lifecycle-manager/issues/226
