### ISSUE TITLE
Show upgrade notification to customers before Kyma upgrade is applied

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/cli#1350]
**Description**

Currently are no upgrade notifications shown to customers when they upgrade their Kyma version over the Kyma CLI.

This has to be improved to provide more transparency about coming changes and migration actions. Kyma publishes changes between releases in its release notes and the Kyma CLI should use this information and inform the customer about coming/available changes in Kyma and potential migration steps.

AC:
* CLI checks the installed Kyma version and shows customer a hint that a new Kyma version is available
    * The check for the current version / available version should not lead to bigger interruptions in our user experience and be stopped if they take more than 250ms
    * The hint about a new Kyma version should only be shown once per day
    * A new command should be added which enables customers to check for new available Kyma versions
* If the customer calls `kyma deploy`, the CLI has to verify if an upgrade will happen and
    * check if the two versions are compatible and can be upgraded (upgrade of >1 major version is not supported and has to be blocked)
    * the release notes of the target version have to be accessible for the customer (show customer a link to the published release-notes page on the KYma website, e.g. https://kyma-project.io/blog/2022/8/25/release-notes-26) together with a short explanation text.
       ```
       You are going to upgrade your Kyma runtime for version a.b.c to x.y.z.

       To learn about upcoming changes and mandatory upgrade steps, read the release notes: [https://kyma-project.io/blog/.../../../release-notes-123](https://kyma-project.io/release-notes-123)
       ```
       
    * customers have to be asked whether the upgrade should be applied via a console prompt (if Kyma CLI is called in non-interactive mode, the upgrade is per default applied).

**Reasons**

Make upgrade processes more transparent and provide customers a summary of the coming changes before the Kyma installation gets updated.

**Attachments**
https://github.com/kyma-project/kyma/issues/15033

**Comment by NHingerl** [comment]
Instead of 

> You are going to upgrade your Kyma runtime for version a.b.c to  x.y.z.
> 
> Please check the release notes for coming changes and required upgrade steps:  https://kyma-project.io/blog/.../../../release-notes-123

I suggest

> You are going to upgrade your Kyma runtime for version a.b.c to  x.y.z.
> 
> To learn about upcoming changes and mandatory upgrade steps, read the release notes: https://kyma-project.io/blog/.../../../release-notes-123

**Comment by jakobmoellersap** [comment]
This is tracked as in progress without assignee, any updates on this?

**Comment by janmedrek** [comment]
Closing this one, we will not invest in that before the modularization is here, and after it won't be needed anymore.
