### ISSUE TITLE
Creating the Module with `kyma alpha mod create` with an empty binary layer causes certain OCI Registry Providers to error out while pushing

### ISSUE THREAD

**Issue by jakobmoellerdev** [kyma-project/cli#1354]
**Description**

It is a valid scenario to build modules with an empty `config.yaml` in the module root directory.

However, the create module command working against GCP artifacts registry is causing a side-effect when trying to bundle a module with an empty `config.yaml` in the module root

```sh
X Pushing image to "europe-west3-docker.pkg.dev/sap-kyma-jellyfish-dev/operator-test"
Error: unable to push layer: failed commit on ref "custom-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855": unexpected status: 400 Bad Request
```

**Steps to reproduce**
1. Use the template operator and generate a module with an empty `config.yaml`
2. Try to push it into GCR / GAR
3. Observe the error when invoking `kyma alpha mod create`

Sample command:
```
kyma alpha create module kyma.project.io/module/template 0.0.0 . \
                --registry https://europe-west3-docker.pkg.dev/sap-kyma-jellyfish-dev/kyma-operator \
                --credentials oauth2accesstoken:[token]
                -w \
                -v
```

Acceptance Criteria:

- [ ] Make sure that OCI Modules generated by CLI are usable even when providing an empty config

**Comment by jeremyharisch** [comment]
Not valid anymore - ConfigLayer will be removed from Module creation, see https://github.com/kyma-project/cli/issues/1684
