### ISSUE TITLE
Provision k3d with cni enabled by default

### ISSUE THREAD

**Issue by strekm** [kyma-project/cli#1373]
**Description**

For Kyma 2.8 Istio will be bumped to Istio 1.15 and Istio cni plugin will be used instead of Istio init-containers. Because of that for k3d provisioning additional setup needs to be done: enabling cni plugin via kubelet params. 

ACs:
- [x] cni is enabled for k3d cluster
- [x] kyma 2.6 installs / upgrades (no Istio cni is used)
- [x] kyma with Istio using cni plugin installs / upgrades

**Reasons**

Security improvements

**Attachments**

part of: https://github.com/kyma-project/kyma/issues/15347

**PR with the change**
- https://github.com/kyma-project/cli/pull/1383

**Comment by barchw** [comment]
Cli PR: https://github.com/kyma-project/cli/pull/1383
