### ISSUE TITLE
`create module`: Generate minimalistic RBAC definition for new modules

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/cli#1380]
**Description**

RBAC is usually a mandatory part of new modules and the `create module` command should also generate an initial RBAC file which will become part of the module manifest (feedback we got from @m00g3n ).

AC:
* Generate RBAC template file when creating a new module with minimalistic permissions.

**Reasons**

Make sure RBAC rules are defined for each Kyma module.

**Attachments**

**Comment by jakobmoellersap** [comment]
Which type of RBAC rules are applied here? Usually all RBAC definitions from the operator are already included in kubebuilder

**Comment by m00g3n** [comment]
The steps to reproduce are:

1.  clone repo `git clone https://github.com/kyma-project/keda-manager.git && cd keda-manager/operator`
1. `make build`
1. `make docker-build IMG=keda-manager:001`
1. create k3d cluster `k3d cluster create testme --registry-create k3d-testme-registry`
1. import image to the cluster `k3d image import keda-manager:001 -c testme`
1. deploy operator `make deploy IMG=keda-manager:001`

The result:
```
1.6648808748852596e+09  INFO    chart located   {"controller": "keda", "controllerGroup": "operator.kyma-project.io", "controllerKind": "Keda", "keda": {"name":"keda-sample","namespace":"def
ault"}, "namespace": "default", "name": "keda-sample", "reconcileID": "c89a5758-8c04-476a-bbc6-1ba274021185", "path": "./module-chart"}
1.6648808760521393e+09  ERROR   error while installing resource default/keda-sample     {"controller": "keda", "controllerGroup": "operator.kyma-project.io", "controllerKind": "Keda", "keda"
: {"name":"keda-sample","namespace":"default"}, "namespace": "default", "name": "keda-sample", "reconcileID": "c89a5758-8c04-476a-bbc6-1ba274021185", "error": "could not render existing reso
urces from manifest: could not get information about the resource keda-manager / keda: serviceaccounts \"keda-manager\" is forbidden: User \"system:serviceaccount:operator-system:operator-co
ntroller-manager\" cannot get resource \"serviceaccounts\" in API group \"\" in the namespace \"keda\""}
github.com/kyma-project/module-manager/operator/pkg/declarative.(*ManifestReconciler).Reconcile
```

**Comment by jakobmoellersap** [comment]
This is a resource that is added on top of our default tooling. This means you will have to manually add the permission in your kubebuilder operator:

https://github.com/kyma-project/keda-manager/blob/main/operator/controllers/keda_controller.go#L53

Here you are missing the `get` permission, you only have `list`.

Please verify if this fixes your issue

**Comment by jakobmoellersap** [comment]
Closing as I expect this was fixed
