### ISSUE TITLE
`nightly-main-reconciler-publish-unstable-cli` can't load `fmt`

### ISSUE THREAD

**Issue by jeremyharisch** [kyma-project/cli#1381]
**Description**
The pipeline `nightly-main-reconciler-publish-unstable-cli` is failing due to the following issue:
```
panic: load embedded ruleguard rules: rules/rules.go:13: can't load fmt
```

Please have a look at the logs:
https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/nightly-main-reconciler-publish-unstable-cli

**Expected result**
Go-Lint should run through.

**Comment by clebs** [comment]
The issue is caused by an incompatibility of `golangci-lint` 1.45 with go 1.18.
Updated the linter and fixed all new linting issues.
