### ISSUE TITLE
Provide a convenient way of interacting with modules in SKR/OS

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/cli#1433]
**Description**

Users will soon experience modularization in the Kyma environments, in this case, both SKR and OS are accounted for. We need to provide a convenient way of working in that ecosystem.

Since Kyma will shift even more towards being a set of building blocks, we want the users to be able to clearly see what modules are installed in their cluster, provide an easy way to modify that list, and interact with specific modules by changing their configuration.

**Acceptance Criteria**
- [x] #1327
- [x] #1328 
- [x] #1432

**Reasons**

We want users to have a good user experience when interacting with modules.

**Comment by jakobmoellersap** [comment]
Could we clarify what we want to deliver with Busola only and what we want to achieve with parity? I could imagine that almost all commands are possible with native kubectl and/or busola ui extensions.

**Comment by janmedrek** [comment]
@jakobmoellersap my point is to have one tool that the users can use throughout their whole workflow. Some parts will not be covered by the CLI (such as creating Functions or configuring Eventing Subscriptions), though, if we can simplify the basic stuff a little bit then it would be beneficial.

Most of the in-depth stuff can indeed be covered via the kubectl commands and the Busola UI, though the basic commands (enable/disable/list/???) should IMHO also be available in the CLI for the convenience of using that in the pipelines or local development.

As for the sub-commands support - we still need to discuss it and make a decision on what direction we want to go.

**Comment by jakobmoellersap** [comment]
We didn't achieve the planned timeline of 31. Jan here, we will have to shift it for about 1 week to 3.2.23 due to https://github.com/kyma-project/cli/issues/1328

**Comment by jakobmoellersap** [comment]
Enable / Disable still not provided, having to push out timeline once again to 10.2.23
