### ISSUE TITLE
Failing Pipeline: nightly-main-reconciler-publish-unstable-cli - Timout while waiting for fakes

### ISSUE THREAD

**Issue by jeremyharisch** [kyma-project/cli#1442]
**Description**
The pipeline `nightly-main-reconciler-publish-unstable-cli` is failling constantly since a couple of days.

https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/nightly-main-reconciler-publish-unstable-cli

Failing reason:

```
--- FAIL: TestWatchResource (0.07s)
    client_test.go:215: 
        	Error Trace:	/home/prow/go/src/github.com/kyma-project/cli/internal/kube/client_test.go:215
        	Error:      	Received unexpected error:
        	            	Timeout reached while waiting for fakes
        	Test:       	TestWatchResource
```

**Expected result**
Test should succeed.

**Comment by janmedrek** [comment]
The pipeline is green once again, closing this issue.
