### ISSUE TITLE
Kyma CLI cannot connect to GKE cluster

### ISSUE THREAD

**Issue by dariusztutaj** [kyma-project/cli#1446]
**Description**

Kyma CLI is not able to properly authenticate for GKE cluster. 
Gcloud components are updated, Kubectl is properly configured and working fine

**Expected result**

_kyma version_ returns Kyma version on the cluster.

**Actual result**
```
Kyma CLI version: 2.8.2
Error: Cannot initialize the Kubernetes client. Make sure your kubeconfig is valid: no Auth Provider found for name "gcp"
```
```
Kyma CLI version: main-f0e97f7
Error: Cannot initialize the Kubernetes client. Make sure your kubeconfig is valid: no Auth Provider found for name "gcp"
```

**Steps to reproduce**

- Deploy GKE cluster
- Deploy Kyma in this cluster

**Troubleshooting**

**Comment by janmedrek** [comment]
Did you run `gcloud auth login` before executing the CLI commands? I believe that would be the first step, if you did - then we may indeed have a problem in the CLI.

CLI does not provide provider-specific auth support, we rely on the fact that the kubeconfig that you provide for interacting with the cluster is valid and has all the necessary privileges to do so.
