### ISSUE TITLE
k3d coredns config disallows hostname lookup via http in local setup

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/cli#1454]
**Description**

Provide a necessary coredns setup that allows to lookup local k3d registry (that is created by kyma provision command ) under `k3d-kyma-registry.localhost` hostname

The `.localhost` suffix is needed as module manager is able fetch from local k3d registry via http only if it is suffixed with `.localhost`. This comes directly from the inherent design of [k3d registries](https://k3d.io/v4.4.8/usage/guides/registries/ )

Kyma CLI provision command does not create `k3d-kyma-registry.localhost` but  `k3d-kyma-registry` and such registry is expected when running `kyma deploy` command.

**Expected result**

Coredns config should allow module manager to resolve `k3d-kyma-registry.localhost` and  fetch module images from local registry when a local setup is provisioned using kyma cli commands:

```
kyma provision k3d
kyma alpha deploy
```

**Actual result**

Currently when using kyma cli to test modular kyma locally we get host lookup error for `k3d-kyma-registry.localhost`

```bash
kyma provision k3d
kyma alpha deploy
```

Logs from module manager:
```
{"level":"ERROR","date":"2022-11-22T15:16:14.905635473Z","caller":"controller/controller.go:326","msg":"Reconciler error","context":{"controller":"manifest","controllerGroup":"operator.kyma-project.io","controllerKind":"Manifest","manifest":{"name":"default-kyma-keda","namespace":"kcp-system"},"namespace":"kcp-system","name":"default-kyma-keda","reconcileID":"1e888190-b0ac-404f-9b04-c24623bddb55","error":"Get \"https://k3d-kyma-registry.localhost:5000/v2/\": dial tcp: lookup k3d-kyma-registry.localhost on 10.43.0.10:53: no such host; Get \"http://k3d-kyma-registry.localhost:5000/v2/\": dial tcp: lookup k3d-kyma-registry.localhost on 10.43.0.10:53: no such host"},"stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:326\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234"}
```

**Related issue(s)**
Found by https://github.com/kyma-project/keda-manager/issues/57

**Comment by nesmabadr** [comment]
This issue was already fixed in this [PR](https://github.com/kyma-project/cli/pull/1455)
