### ISSUE TITLE
Avoid hardcoded domains for `provision minikube` command

### ISSUE THREAD

**Issue by pkosiec** [kyma-project/cli#147]
**Description**

I just wanted to include `compass` chart in Kyma sources, but I’ve seen that currently the list of domain is hardcoded in CLI code:
https://github.com/kyma-project/cli/blob/master/pkg/kyma/cmd/provision/minikube/cmd.go#L27

It would be better to list VirtualServices from system namespaces after Kyma minikube installation and add every URL to /etc/hosts. Basically, it could iterate over all VirtualServices which has `.kyma.local` domain.

**Reasons**

It’s inconvenient to modify sources for the CLI while adding new component to Kyma which has some URL exposed.

**Comment by a-thaler** [comment]
A very good idea, I like it! By moving the local setup phase to the end of the install command, it will be possible to get the list of domains from the cluster. I added the idea to https://github.com/kyma-project/cli/issues/175

**Comment by suleymanakbas91** [comment]
Solved by #212.
