### ISSUE TITLE
Kyma CLI complains on missing `kustomize` binary

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/cli#1470]
**Description**

Kyma CLI complains on missing `kustomize` binary. I had to add kustomize manually to ~/.kyma/bin folder to continue.

**Expected result**

Kustomize is downloaded automatically or user is instructed what to do.

**Actual result**

```
kyma alpha create module --version 0.0.1 -w  --registry myregistry
WARNING: This command is experimental and might change in its final version. Use at your own risk.
X Parse and build module...
Error: could not edit kustomization image: error getting kustomize binary: exec: "/Users/myuser/.kyma/kustomize": stat /Users/myuser/.kyma/kustomize: no such file or directory
```

**Comment by Tomasz-Smelcerz-SAP** [comment]
Confirmed. The `kustomize` binary is not installed in the setup of the `alpha create module` command.
