### ISSUE TITLE
missing serverless functions when using kyma dashboard command

### ISSUE THREAD

**Issue by hokandil** [kyma-project/cli#1483]
I am trying to to run Kyma dashboard locally on my K3d Cluster provision by kyma cli command
`kyma provision k3d`
I used to use the command 
`kyma dashboard` 
to run the dashboard , but now the dashboard appears to open in a mode that no kyma functionalities is enabled , only default kubernetes resources are there . there is no serverless functions , no api rules although I can still access thies resources through kubectl command.

![image](https://user-images.githubusercontent.com/28161747/208242682-c81e54b0-fb38-4463-8e76-615348b718a0.png)

**Comment by kwiatekus** [comment]
From the description you provided it seems that you havent deploy kyma.
```
kyma provision k3d
kyma deploy // <-- missing
kyma dashboard
```

**Comment by hokandil** [comment]
> From the description you provided it seems that you havent deploy kyma.
> 
> ```
> kyma provision k3d
> kyma deploy // <-- missing
> kyma dashboard
> ```

Definitely I deployed kyma. Anyway it was a bug in that release and fixed the same day I posted this issue.  Now it is working as you knew every time you use that kyma dashboard command it downloads the latest docker image if any.
