### ISSUE TITLE
unstable-cli redundant builds

### ISSUE THREAD

**Issue by Tomasz-Smelcerz-SAP** [kyma-project/cli#1487]
**Description**

There are two jobs to build `unstable-cli`: the post-submit job named `unstable-cli` and the periodic job named `nightly-main-reconciler-publish-unstable-cli`

We should be able to build and publish the unstable cli with only one job, preferrably a post-submit.

**Reasons**

We need to maintain and watch two different jobs

**Comment by LeelaChacha** [comment]
[PR created in test infra repo](https://github.com/kyma-project/test-infra/pull/7822)
