### ISSUE TITLE
Stable k3d coredns customization on restarts

### ISSUE THREAD

**Issue by johgoe** [kyma-project/cli#1497]
**Description**

Currently core dns have to be patched every time by kyma cli again, to make it work. If a k3d is restarted itself, the cluster is broken an must be patched again. This can be fixed if the core dns is not patched but using s custom config map.

**Reasons**
K3D writes the coredns config map on every restart to fix the new ip addresses of every node.

See this PR to get an idea how to fix the kyma coredns settings without patching it on every restart:
https://github.com/k3s-io/k3s/pull/4397

**Attachments**

**Comment by janmedrek** [comment]
Stopping the development according to: https://github.com/kyma-project/community/issues/872
