### ISSUE TITLE
Kyma alpha deploy dashboard does not open correctly

### ISSUE THREAD

**Issue by jakobmoellersap** [kyma-project/cli#1503]
**Description**

When using `kyma provision k3d`, then `kyma alpha deploy`, the following page is displayed:
<img width="688" alt="image" src="https://user-images.githubusercontent.com/64904610/214521070-4e4a8cc5-3cc7-4265-83ca-8e1e8dbb78e6.png">

This can be reset by hard reloading the page, however the context is not injected correctly:

<img width="1299" alt="image" src="https://user-images.githubusercontent.com/64904610/214521242-6c21fa35-2f8b-4523-93ca-3d8aa26ad2fe.png">

**Expected result**

I would like to have busola open a loading page with a working kubeconfig already injected. 

**Actual result**

The Page with Busola does not load first try
Even after reloading manually, the kubeconfig is still not accepted.

**Steps to reproduce**

1. `kyma provision k3d`
2. `kyma alpha deploy`
3. Get redirected to erroring browser window

**Troubleshooting**

Reproducible with latest stable/unstable

Hard Reloading allows busola to load, but kubeconfig is still invalid and there is no detailed error message available in the dialog.

**Comment by mrCherry97** [comment]
Hi @jakobmoellersap 
fix is pushed and everything should work now. Please take a look, and if problem appears please reopen the issue.
