### ISSUE TITLE
`kyma-unstable alpha create module` unable to push to gcp artifact registry

### ISSUE THREAD

**Issue by dariusztutaj** [kyma-project/cli#1523]
**Description**
When building module manually I'm getting error: `Error: unable to push layer: failed to copy: io: read/write on closed pipe`
I authenticated request with oauth2accesstoken and json token and got the same result.

**Expected result**
Module successfully pushed to artifact registry

**Actual result**
```
➜  istio git:(main) ✗ /Users/I552063/tmp/lcm/istio-default/istio/bin/kyma-unstable alpha create module --channel=alpha --name kyma-project.io/module/istio --version 0.0.1 --path . --registry europe-central2-docker.pkg.dev/sap-se-cx-kyma-goat/istio -w -c oauth2accesstoken:${GCR_DOCKER_PASSWORD} --verbose
WARNING: This command is experimental and might change in its final version. Use at your own risk.
- Kustomize ready
/ Parse and build module...2023-02-10T10:01:07.745+0100	DEBUG	module/resources.go:161	Inspecting module contents at [/Users/I552063/Documents/projects/github.com/kyma-project/istio]:
2023-02-10T10:01:07.745+0100	DEBUG	module/resources.go:184	No kubebuilder project detected, bundling module in a single layer.
2023-02-10T10:01:07.745+0100	DEBUG	module/resources.go:296	Added layer {name:istio resourceType:helm-chart path:/Users/I552063/Documents/projects/github.com/kyma-project/istio excludedFiles:[]}
- Module built
- Default CR validation succeeded
- Creating module archive at "./mod"
/ Creating image...2023-02-10T10:01:07.748+0100	DEBUG	module/resources.go:118	Generated resource:
access: null
input:
  compress: true
  path: /Users/I552063/Documents/projects/github.com/kyma-project/istio
  type: dir
name: istio
relation: local
type: helm-chart
version: 0.0.1

2023-02-10T10:01:07.748+0100	DEBUG	module/resources.go:44	Adding 1 resources...
2023-02-10T10:01:07.748+0100	DEBUG	module/resources.go:47	Added input blob from "/Users/I552063/Documents/projects/github.com/kyma-project/istio"
\ Creating image...2023-02-10T10:03:24.267+0100	DEBUG	module/resources.go:74	Successfully added resource to component descriptor
2023-02-10T10:03:24.267+0100	DEBUG	module/resources.go:76	Successfully added all resources to component descriptor
- Image created
X Pushing image to "europe-central2-docker.pkg.dev/sap-se-cx-kyma-goat/istio"
Error: unable to push layer: failed to copy: io: read/write on closed pipe
```

**Comment by dariusztutaj** [comment]
@kyma-project/jellyfish Could you help me with this?

**Comment by Tomasz-Smelcerz-SAP** [comment]
@dariusztutaj `kyma-unstable` may be a bit obsolete (last build about week ago). For `alpha` commands it's always best to use the latest CLI - just build a binary locally, it takes no more than 5 minutes and is as simple as `make build-darwin` (if you're on Mac). By doing so you'll have the latest patches and bugfixes.

**Comment by Tomasz-Smelcerz-SAP** [comment]
OK, I've just verified that the lates `kyma-cli` works fine with our [template-operator](https://github.com/kyma-project/template-operator).
Can you verify if that works for you? Perhaps there's a problem with your tooling, we can detect if the "happy path" scenario works for you.

Sequence of steps:

1) Go to gcloud console (Web UI) and create new artifact repository in your gcloud project. Mine project is : `sap-kyma-jellyfish-dev`, I've created a repository: `tsm-test`
2) Checkout latest [kyma-cli ](https://github.com/kyma-project/cli) (main branch)
3) `make build-darwin` (if you're on a Mac)
4) Checkout [template-operator](https://github.com/kyma-project/template-operator)
5) cd to `template-operator` project directory
6) `alias kyma="$GOPATH/src/github.com/kyma-project/cli/bin/kyma-darwin"` (adjust if necessary)
7) login to gcloud in the terminal: `gcloud auth login`
8) Get your token. Don't share it, it carries your user priviledges! `export GCR_DOCKER_PASSWORD=$(gcloud auth print-access-token)`
9) `kyma alpha create module -v --version 0.0.21 -w --registry europe-west3-docker.pkg.dev/sap-kyma-jellyfish-dev/tsm-test/foo -c "oauth2accesstoken:$GCR_DOCKER_PASSWORD"` Adjust the project and repository name.

**Comment by dariusztutaj** [comment]
Even with latest kyma, built from main, I'm getting exactly the same error:
```
X Pushing image to "europe-central2-docker.pkg.dev/sap-se-cx-kyma-goat/istio"
Error: unable to push layer: failed to copy: io: read/write on closed pipe
```
My question is how can I raise debug level for pushing part?

**Comment by Tomasz-Smelcerz-SAP** [comment]
I don't think we have debug statements there... The only way would be to add such debugging info, or even run the CLI in the debugger to see which layer is affected.

**Comment by Tomasz-Smelcerz-SAP** [comment]
But did you run all the steps I provided, with the `template-operator`? Because if it doesn't work with the `template-operator`, it means there's a problem with your environment and maybe we should extend the CLI to account for this. If it works with `template-operator` then I think the problem is related to the structure of the module you're trying to push (maybe something is missing). Then it may be more related to unclear documentation than any real bug in the CLI.

**Comment by dariusztutaj** [comment]
With manually built cli it's working
