### ISSUE TITLE
Improve how single cluster mode is usable in CLI

### ISSUE THREAD

**Issue by jakobmoellersap** [kyma-project/cli#1549]
**Description**

When using `kyma alpha deploy`, we currently do not deploy any module templates. However the module templates available in https://github.com/kyma-project/kyma/blob/main/modules/kustomization.yaml do not use target `control-plane` but target `remote`. This means that by default the CLI sets up only one cluster as control-plane, but the ModuleTemplates available are setup for dual-cluster mode.

**Reasons**

We should find a way to unify this setup so that we are able to deal with both scenarios without relying on many user modifications of `ModuleTemplate` (if any at all).

That will ease the adoption process for the Modularization concept and make sure people can use their clusters out of the box.

**Attachments**

**Comment by ruanxin** [comment]
My proposal is to introduce a global flag for lifecycle-manager to config it in dual or single mode (by default use dual mode), if it's single mode, lifecycle manager just ignores the `target` fields when processing the module template. If it's in single mode, this field does not make any sense, right? 

To achieve this, we can introduce a kustomize single mode config in lifecycle-manager in cli with a patch to the lifecycle-manager Deployment yaml contains single mode flag, then config a cli flag to choose dual or single mode, if single mode enabled, cli choose to deploy this single mode kustomize config.

**Comment by jakobmoellersap** [comment]
If we use a flag, imo the API fields become useless. Thus, I suggest we somehow make it usable with either new fields or the existing fields in the ModuleTemplates

**Comment by jakobmoellersap** [comment]
This is complete, by default the CLI now writes module templates with control-plane target. also a wildcard role is added
