### ISSUE TITLE
Update default version for K8s clusters in Kyma CLI to 1.25 (due: Next rel.2.11.Hotfix. perh.28.02.2023 )

### ISSUE THREAD

**Issue by zhoujing2022** [kyma-project/cli#1555]
Description

This is the action agreed with release management for the coming K8s cluster version upgrade to 1.25.

See https://github.com/kyma-project/kyma/issues/16568

We have to update the default version in the CLI kyma provision command to create a 1.25 K8s cluster in Gardener and when using K3d.

Could be worth to centralise the K8s cluster version so that only a sigle place needs to be changed in the futuer (current findings for K8s cluster versions: https://github.com/kyma-project/cli/search?q=1.24).

AC:

when creating a K3d cluster, the default cluster version is 1.25
when provisioning a Gardener cluster, the default cluster version is also 1.25

**Comment by janmedrek** [comment]
PR: https://github.com/kyma-project/cli/pull/1557/files
