### ISSUE TITLE
CLI edit operator kustomization.yaml file

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/cli#1556]
The CLI alpha create command will add an image entry in the operator config/kustomization.yaml, this process should be prevented.

I removed this misplaced entry in this PR:
https://github.com/kyma-project/template-operator/pull/27/files#diff-c006b1ef995eeeb57408cce42bd84db8dfc0cbe18df03222857665cebb1ac6fdL84

**Comment by jakobmoellersap** [comment]
This bug was fixed https://github.com/kyma-project/cli/commit/32ae168b1acd05225232869c446da76a0b1a55d4
