### ISSUE TITLE
CLI Alpha command E2E Testing with Template Operator

### ISSUE THREAD

**Issue by jakobmoellerdev** [kyma-project/cli#1567]
Description:

As a Kyma CLI user, I would like to ensure that my operators designed to be used within Kyma, are compatible with lifecycle-manager, and also that all commands that are used in the new ecosystem are always working with a reference Module implementation (in our case https://github.com/kyma-project/template-operator).

AC:
- [x] Create a GH-Action based Pipeline that uses template-operator with `kyma alpha deploy/enable/disable` to completely verify the module lifecycle. (pre-merge pipeline)
- [x] Check that template-operator resources are created correctly if enabled
- [x] Check that template-operator resources are gone if disabled completely, but with CRDs still intact
- [x] Enable template-operator with Warning state, check if CLI return exist with code 2, related issue https://github.com/kyma-project/cli/issues/1683 
- [x] Pair with @ameteiko to design test suit
- [x] e2e Suite should compile binary for CLI and use this 
- [x] Reuse and rename current smoke-test-workflow

**Comment by jeremyharisch** [comment]
Blocked by https://github.com/kyma-project/cli/issues/1684

**Comment by janmedrek** [comment]
@medmes please provide a new description or divide this issue into the smaller ones.
