### ISSUE TITLE
Kyma cli Print summary is wrong

### ISSUE THREAD

**Issue by rakesh-garimella** [kyma-project/cli#1568]
**Description**
When we install kyma using cli in the print summary it shows how long it took for the kyma integration. The duration shown is wrong now
```
Kyma installation took:		3 minutes222 seconds
```

**Expected result**
The installation duration is shown properly 

**Steps to reproduce**
Install kyma using cli

**Comment by dbadura** [comment]
The same happen to me: `Kyma installation took:		1 minutes101 seconds`

**Comment by nesmabadr** [comment]
This was fixed in this [PR](https://github.com/kyma-project/cli/commit/2900b0b961b9b9f3a11e77775ad828d873705d74#diff-572f36eb419ff9c9849f98b236a7abb220e73f0e495f16d921619de19ae1b898L70)
