### ISSUE TITLE
kyma enable module command should validate channel.

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/cli#1577]
**Description**

If enable module command give non exists channel, it will indicate patch success.
The next command which gives a correct channel will not overwrite this wrong channel, and still indicate patch success.

**Expected result**

enable module should validate if the given channel is valid.

**Steps to reproduce**
First given a run channel
```
kyma alpha enable module keda -c wrongchannel -n kcp-system -k default-kyma
```
it will show patch success
```
Modules patched! (22ms)
```

**Troubleshooting**

**Comment by jakobmoellersap** [comment]
I think we have an issue here determining what a "valid" channel is. The only way to determine all available channels is by aggregating over the ModuleTemplates and then choosing the right channel. We could use that as our value help then.
