### ISSUE TITLE
Remove kubectl binary usage

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/cli#158]
**Description**
In https://github.com/kyma-project/cli/issues/85 the main parts of kubectl binary usage were replaced. Still left are all apply methods (for the installer.yaml, tiller.yaml and overrides). Furthermore, all management of the installer installation resource is still based on the binary.

**Reasons**
Consistent usage of kubectl library instead of binary, see also https://github.com/kyma-project/cli/issues/85

**Comment by suleymanakbas91** [comment]
Implemented with https://github.com/kyma-project/cli/pull/470.
