### ISSUE TITLE
Provisioning minikube on linux fails

### ISSUE THREAD

**Issue by tgorgol** [kyma-project/cli#159]
**Description**

Using `kyma provision minikube` command on linux results in error because `sed` command used by the program is compatible only with BSD sed and not with GNU sed.

**Expected result**

Sed command should work.

**Actual result**

Sed command doesn't work.

Logs of a prow job that tried installing kyma on linux by using kyma cli: https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-incubator_compass/112/pre-master-compass-integration/1148512714004369408/build-log.txt

See:
```
- Minikube up and running
  Adding domain mappings to your 'hosts' file
  You're running CLI with sudo. CLI has to add Kyma domain entries to your 'hosts'. Type 'y' to allow this action
Type [y/n]:   Error: Failed executing command 'sudo [sed -i '' /kyma.local/d /etc/hosts]' with output 'sed: -e expression #1, char 1: unknown command: `''
' and error message 'exit status 1'
  Execute the following command manually to add domain entries:
###
 sudo sed -i '' "/kyma.local/d" /etc/hosts && echo '10.164.0.28 apiserver.kyma.local console.kyma.local catalog.kyma.local instances.kyma.local brokers.kyma.local dex.kyma.local docs.kyma.local lambdas-ui.kyma.local console-backend.kyma.local minio.kyma.local jaeger.kyma.local grafana.kyma.local configurations-generator.kyma.local gateway.kyma.local connector-service.kyma.local log-ui.kyma.local loki.kyma.local kiali.kyma.local compass-gateway.kyma.local' | sudo tee -a /etc/hosts
###
````

**Steps to reproduce**

Run `kyma provision minikube` on linux. 

**Troubleshooting**

#160 
Logs of prow job using code from linked PR, where the problem no longer occurs: https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-incubator_compass/112/pre-master-compass-integration/1148516015391379456/build-log.txt

**Comment by a-thaler** [comment]
Thanks for providing the fix
