### ISSUE TITLE
can not provision gardener with kubernetes version 1.26

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/cli#1609]
**Description**

At the moment, if the provision gardener shoot with `--kube-version=1.26.1`, it will error out to complaining kubeconfig secret can't find.

The root cause for this is after upgrading to 1.26, seems the gardener API contract by default disabled the static token kubeconfig. However, this field is `true` when provisioning with k8s version 1.25

```
  kubernetes:
    enableStaticTokenKubeconfig: false
```

```
- Validating flags (0s)
- Provisioning Gardener(GCP) cluster (6m15.757s)
X Importing kubeconfig (51ms)
Error: secrets "k8s1261.kubeconfig" not found
```

AC:
- [ ] make this `enableStaticTokenKubeconfig` configurable as a CLI flag with bool type, by default set to `true`.
- [ ] adjust current cli provision logic, if this flag is configured to `false`, still possible to finish the provision.

**Steps to reproduce**

run the following command on local machine
```
kyma provision gardener gcp --secret [gardener project secret] --name [shoot name] --project [gardener project] --credentials [gardener credentials] --kube-version 1.26.1 --verbose
```

**Comment by nesmabadr** [comment]
Based on the [Gardener docs](https://github.com/gardener/gardener/blob/master/docs/usage/shoot_access.md), starting from Kubernetes 1.27, the `enableStaticTokenKubeconfig` will be locked to false. Accordingly, the cli flag is no longer needed. This ticket just tackles how the kubeconfig is generated and imported using the `shoots/adminkubeconfig subresource`.

**Comment by ruanxin** [comment]
CLI dependency - hydroform should be upgraded
