### ISSUE TITLE
Feature Flag to skip CRD installation of monitoring and tracing

### ISSUE THREAD

**Issue by johgoe** [kyma-project/cli#1631]
This feature is required to fix https://github.com/kyma-project/kyma/issues/17214 which breaks the whole monitoring Installation, if the deprecated components for logging and tracing are already replaced with own helm charts and a newer version.

**Comment by johgoe** [comment]
It happened again during the update to kyma 2.13

**Comment by janmedrek** [comment]
Hey @johgoe, can you provide more description for this feature request?

To be honest I am not sure what is expected from the CLI here, I would rather avoid adding flags for skipping the installation of one specific component. We are also going away from the old approach in favour of the modular approach, please let us know what is the importance of this request as well.

**Comment by johgoe** [comment]
@janmedrek I'm not an expert about kyma but your kyma collegues did already did an analyse in https://github.com/kyma-project/kyma/issues/17214 with the conclusion that the bug is within CLI. But nothing happen and 2.13 is still broken. That's why I thougth that it's better to inform the CLI project with this issue. 
The problem is a major issue for all kyma project users, which have to switch from integrated kyma solution to a own manage kube-loki-stack because the CRDs Versions in kyma are very old but kyma cli always overrides all CRDs even if monitoring and tracing is not part of the installation.

The reason why kyma-project users disable monitoring and tracing component is, that they are forced to be prepared because of the deprecation of this kind of components within the kyma-project.

**Comment by janmedrek** [comment]
This won't be worked on as modularization of monitoring and tracing was finalized.
