### ISSUE TITLE
Remove the name prefix in `create module` command

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/cli#1638]
**Description**

Remove the `moduletemplate-` prefix that is automatically added to the ModuleTemplate name after executing `kyma alpha create module` command.

**Reasons**

This prefix is redundant and does not provide any additional value. In fact, it may cause confusion and make it more difficult for users to quickly identify the name of the ModuleTemplate. Removing this prefix would simplify the naming convention and make it more intuitive for users.

**Attachments**

N/A

**Comment by ruanxin** [comment]
already implemented
