### ISSUE TITLE
Ask for user password  in advance during minikube provisioning

### ISSUE THREAD

**Issue by sjanota** [kyma-project/cli#168]
**Description**

Users should be able to provide a password to `kyma provision minikube` at the beginning. 

**Reasons**

Now the user is asked for the password when it is needed. As it is at the end of the installation one can easily forget about it. Having the prompt at the beginning the user could queue commands like this: `kyma provision minikube; kyma install` and forget about the installation for a while.

**Attachments**

**Comment by a-thaler** [comment]
We plan to restructure the provision/install phases a bit. That includes that all local setup will happen as last step of install phase only. With that your scenario will be solved. See https://github.com/kyma-project/cli/issues/175

**Comment by suleymanakbas91** [comment]
Solved by #212. Now the password will only be asked at the end of the installation.
