### ISSUE TITLE
Failing `unstable-cli` due to permission denied error

### ISSUE THREAD

**Issue by fourthisle** [kyma-project/cli#1681]
**Description**
The pipeline [unstable-cli](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/unstable-cli) is failing due to permission denied error.

**Expected result**
Authentication to `gcloud` should succeed.

**Actual result**
Authentication to `gcloud` is failing.
```log
debug1: Authentications that can continue: publickey
debug1: No more authentication methods to try.
sa_117798148653314453801@35.204.166.141: Permission denied (publickey).
```

**Failing Run link**:
https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/unstable-cli/1668939778692747264

**Comment by halamix2** [comment]
SSH is a bit unstable:
* the best solution is to ditch VM for k3d: https://github.com/kyma-project/test-infra/issues/7862
* functions from `uitls.sh` dealing with ssh could be changed to retry on error (currently only `utils::receive_from_vm` retries 5 times, increasing stability)

**Comment by jeremyharisch** [comment]
Will be resolved with: https://github.com/kyma-project/lifecycle-manager/issues/682
