### ISSUE TITLE
Adjust exit codes for the `Warning` state

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/cli#1683]
**Description**

The new introduced `Warning` state of Kyma is treated by the CLI like an error and leads to an exit-code 1.

Unfortunately, the Kyma module release pipeline relies on the exit-code of the CLI to determine whether a Kyma module was properly installed.

The `Warning` state is indicating that a module is correctly installed, but cannot work properly caused by missing configuration parameters (or other required pre-requisites).

We should agree how the CLI will reflect the `Warning` state in the return-code. I would see these two options:

1. `Warning` is handled like `Ready` and leads to an exit-code 0 by the CLI
2. `Warning` is handle individually by the CLI and returns a dedicated exit code, e.g.
    1. `Ready` = exit code 0
    2. `Warning` = exit code 2 (or any other preferred digit >1)
    3. `Error` = exit code 1

Please agree how the CLI will handle the `Warning` state on the exit-code level and inform @the1bit about your agreement. Finally, please update the CLI implementation to respond with the appropriate exit-code if Kyma ends up in a `Warning` state.

**Expected result**

It's possible to detect the Kyma `Warning` state by evaluating the exit-code of the Kyma CLI.

**Actual result**

Kyma CLI returns always exit code 0 if the Kyma state is not `Ready` (or `Error`).

**Steps to reproduce**

Install BTP-operator module via the Kyma CLI. This leads to a Kyma instance in `Warning` state.

**Troubleshooting**

**Comment by ruanxin** [comment]
The e2e test should be implemented in issue https://github.com/kyma-project/cli/issues/1567
