### ISSUE TITLE
Allow for backticks (backquotes) in the CLI command help/usage messages.

### ISSUE THREAD

**Issue by Tomasz-Smelcerz-SAP** [kyma-project/cli#1703]
**Description**

The Kyma-CLI docs in Markdown format are generated automatically from the text messages embedded in the CLI as the command help/usage. The primary use for these messages is to print it out to the user's terminal while interacting with the CLI.

Backticks (backquotes) are used to denote code blocks in Markdown.
Currently, if we include the backtick character in the CLI command help, the command fails with an error:
```
go run cmd/main.go alpha create module --help
# github.com/kyma-project/cli/cmd/kyma/alpha/create/module
cmd/kyma/alpha/create/module/module.go:52:118: syntax error: unexpected -- in composite literal; possibly missing comma or }
cmd/kyma/alpha/create/module/module.go:106:48: syntax error: unexpected ] at end of statement
```
This is because the command help in the CLI is deffined using golang's `raw string literals` that use backticks to denote the literal itself and no backtick can be embedded inside the string.
We also cannot easily switch to standard string literals, because then we have a problem of mulit-line text messages, which are typical for CLI help messages.    

AC:
- Allow to embed backtick characters in the CLI command help output, OR provide a simple workaround so that the generated Markdown docs have proper code blocks - at least for single words or sequences of words (command examples, snippets etc.)

**Reasons**

- better user experience for auto-generated docs vs manually created documentation
- proper code blocks in our web documentation
- One can use the same (or similar) syntax in the `*.md` files AND in the text messages embedded in the CLI.

**Comment by janmedrek** [comment]
Stopping the development according to: https://github.com/kyma-project/community/issues/872
