### ISSUE TITLE
Add missing flags to test run command

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/cli#171]
**Description**
The `test run` command is missing the --timeout, -l/--labels and --delete option.
Also check https://github.com/kyma-project/cli/issues/32
**Reasons**
Have all options of octopus available in CLI

**Comment by mszostok** [comment]
`--timeout` was implemented via this PR: https://github.com/kyma-project/cli/pull/296

**Comment by a-thaler** [comment]
Double-check if the timeout really interrupts test execution, not only the watch process.

**Comment by a-thaler** [comment]
timeout and labels are already available, I don't see a demand to have a delete option, so will close the ticket
