### ISSUE TITLE
Remove the git requirement for create module command

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/cli#1723]
**Description**

Right now, the alpha create module command uses the `.git` directory to import sources description for the ModuleTemplate, this is implicit and not passed as an argument/metadata field.

The goal is to remove that requirement, it should be optional. The sources part is optional in the OCM libraries.

**Acceptance Criteria**

- [x] Alpha create module command does not require to be ran in the git directory
- [x] With non-git repository, security scan configuration should be ignored 
    - Warn the user by letting fail the step, but not error out
      - in CI mode, print warning message in terminal, but not blocked
      - in non CLI mode, print warning message, block and waiting for user interactive, press `enter` or `y` to continue, `n` to quit. 
    -  Source layer should not be created

**Comment by medmes** [comment]
**PR**: https://github.com/kyma-project/cli/pull/1751
