### ISSUE TITLE
Support adding customStateCheck using the Create Module command

### ISSUE THREAD

**Issue by nesmabadr** [kyma-project/cli#1729]
**Description:**

Since the lifecycle-manager now supports the module `customStateCheck` (https://github.com/kyma-project/lifecycle-manager/pull/784), the CLI Create Module command should also support adding the customStateCheck field to the ModuleTemplate.

The docu on the custom state check is [here](https://github.com/kyma-project/lifecycle-manager/blob/main/docs/technical-reference/api/moduleTemplate-cr.md#speccustomstatecheck)

**Acceptance Criteria:**

- [x] Create Module command supports adding the customStateCheck field
- [ ] There is an **optional** config file section for setting up the custom state check and the mappings

**Comment by LeelaChacha** [comment]
blocked by #1752

**Comment by jeremyharisch** [comment]
[#1729](https://github.com/kyma-project/cli/pull/1764) implementation works fine, but not uses the config file. It was implemented introducing new flags.

Needs to be changed:
- Remove flags
- Use config file instead
