### ISSUE TITLE
Error - "module template not allowed: internal module"

### ISSUE THREAD

**Issue by anirudhprasad-sap** [kyma-project/cli#1761]
Hi Colleagues,

We are trying out the create module command by passing the config file. Our config file is as shown below-

```
name: sme.sap.com/cap-operator
channel: fast
version: v1.0.8
manifest: ./manifest_1.0.8.yaml
defaultCR: ./config/samples/operator_v1alpha1_capoperator.yaml
internal: true
annotations:
  operator.kyma-project.io/doc-url: "https://pages.github.tools.sap/erp4sme/cap-operator"
```

We have set the flag internal to 'true' for our module. But on adding the module template to the kyma resource. We are getting the error - 'module template not allowed: internal module'. Please find the attached screenshot of the error-

![image](https://github.com/kyma-project/cli/assets/126493692/08ba1631-d5eb-44c3-b4db-166f0dc583da)

Cluster Details -
Kubernetes: v1.26.5
Kyma: 2.17.0
API Server Address- https://api.d2bba1f.stage.kyma.ondemand.com/

We had raised this issue on [Slack](https://sap-btp.slack.com/archives/C03BC9UVAR1/p1691677571167639) and understood from @janmedrek that label `operator.kyma-project.io/internal:true` needs to be set on the Control Plane Kyma CR to allow installation of the remote internal module templates.

But If I understood correctly from @janmedrek there is no automation for this and this would mean that when we finally release the cap-operator as an internal module, nobody will be able to install it unless the above flag is set on the Control Plane Kyma CR. Or is my understanding wrong? Can you please help?

Thanks and regards,
Anirudh

**Comment by pbochynski** [comment]
The missing feature was implemented in this issue: https://github.com/kyma-project/control-plane/issues/3005
It should work now. @anirudhprasad-sap can you check again?

**Comment by anirudhprasad-sap** [comment]
@pbochynski It is working now. Thanks!
