### ISSUE TITLE
Unexpected repoUrl in moduletemplate.yaml

### ISSUE THREAD

**Issue by the1bit** [kyma-project/cli#1766]
**Description**

Some release earlier when someone generated a Kyma module template with Kyma-Cli the `repoUrl` format was the following:
```yaml
repoUrl: github.com/kyma-project/kyma-module
```

Our other pipelines knows this format. Nevertheless, now the moduletemplate.yaml file contains the following `repoUrl` format:
```yaml
repoUrl: https://github.com/kyma-project/kyma-module.git
```

This blocks our pipelines, because they cannot clone the repo and logging the following messages:
```bash
2023/09/12 08:23:39 check.go:155: Cloning [https://https://github.com/kyma-project/kyma-module.git](https://https//github.com/kyma-project/keda-manager.git)
2023/09/12 08:23:49 check.go:143: Scan failed with error could not clone git repo: Get "[https://https//github.com/kyma-project/kyma-module.git/info/refs?service=git-upload-pack"](https://https//github.com/kyma-project/kyma-module.git/info/refs?service=git-upload-pack%22): dial tcp: lookup timeout
panic: runtime error: invalid memory address or nil pointer dereference
```

**Version**: We used the unstable version which was available at 2023-09-12 08:00:00 CEST.
**OS**: Ubuntu 22.04 - Azure Pipeline

**Expected result**

moduletemplate.yaml file contains the following `repoUrl` format:
```yaml
repoUrl: github.com/kyma-project/kyma-module
```

**Actual result**

moduletemplate.yaml file contains the following `repoUrl` format:
```yaml
repoUrl: https://github.com/kyma-project/kyma-module.git
```
**Steps to reproduce**

Merely, generate a module template:
```bash
kyma alpha create module \
                  --module-config-file ./config.yaml \
                  --registry "************" \
                  --sec-scanners-config ./sec-config.yaml \
                  --module-archive-version-overwrite \
                  --output=moduletemplate.yaml \
                  --registry-cred-selector=*********\
                  --credentials oauth2accesstoken:********
```

**Troubleshooting**

We've started to check to modify the `repoUrl` value parsing in our pipelines.

**Comment by jeremyharisch** [comment]
ACs:
- [ ] Investigate how this change was introduced, make sure its not flaky
- [ ] Communicate to neighbours, what the current standard is

**Comment by jeremyharisch** [comment]
@the1bit we indeed had a small bug which was introduced in the URL path. But it is not what you have described.

Let me explain:
We want to stick to the default of Github which means a repo URL should have the following format: `https://github.com/<project name>/<repository name>.git`

[This PR](https://github.com/kyma-project/cli/pull/1775) includes the `.git` suffix again.

Please adapt your corresponding pipelines using the default Github-URL.
