### ISSUE TITLE
remove `--kubebuilder-project` in CLI

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/cli#1773]
This command is deprecated, we should do the cleanup in the code base for this command.

AC:
- [ ] All code related to `--kubebuilder-project` should be removed.

**Comment by janmedrek** [comment]
This should be a part of next major CLI release, we need to synchronize this change with other deprecations and moving alpha commands to non-alpha.

**Comment by janmedrek** [comment]
Stopping the development according to: https://github.com/kyma-project/community/issues/872
