### ISSUE TITLE
Kyma CLI 2.18 do not install Kyma 2.18 by default

### ISSUE THREAD

**Issue by videlov** [kyma-project/cli#1777]
**Description**

Current latest Kyma CLI (2.18) do not install Kyma from release branch, but from main:

```
Kyma CLI version: 2.18.0
Kyma cluster version: N/A
kyma deploy --ci -c hack/kyma-components.yaml
- No previous Kyma version found
- Using Kyma from the workspace directory: /home/runner/.kyma/sources/main
```

**Expected result**

It should install respective Kyma release version.

**Actual result**

Installs Kyma from main branch

**Steps to reproduce**

In the description

**Troubleshooting**

This might be fixed already, because latest unstable CLI is properly taking latest Kyma released version:

```
Kyma CLI version: main-a4af874
Kyma cluster version: N/A
- Detecting Environment (418ms)
- No previous Kyma version found (282ms)
- Using Kyma from the workspace directory: /Users/d051408/.kyma/sources/2.18.0 (23.748s)
- Initial setup (103ms)
```

**Comment by ruanxin** [comment]
did new release https://github.com/kyma-project/cli/pull/1779
