### ISSUE TITLE
Integration test to assure support of latest kyma revision

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/cli#18]
Have integration tests which are using latest CLI revision (master) with latest revision of Kyma (master).
As the reason for failures are not clearly assignable to a repo, the test should not block any pull request and might be executed on a periodic base reporting to a slack channel.

It should do the same steps as https://github.com/kyma-project/kyma/issues/4048 but should be based on gke

**Comment by sjanota** [comment]
If Kyma tests switch to kyma-cli would that be enough integration test?

**Comment by suleymanakbas91** [comment]
@sjanota not really. For the integration jobs, we'll be using the latest release of Kyma CLI. However, for this one, we'll be using the latest master from both.
