### ISSUE TITLE
Investigate the possibility of automating the CLI release process

### ISSUE THREAD

**Issue by nesmabadr** [kyma-project/cli#1805]
**Description**

Currently, we follow these [guidelines](https://github.com/kyma-project/community/blob/main/docs/guidelines/releases-guidelines/03-kyma-cli-release-process.md) to do a CLI release. We would like to investigate if it's possible to automate this process in a pipeline.

**ACs**

- [ ] Check if possible to have a prow job for the CLI release

**Comment by janmedrek** [comment]
We've decided to put this one on hold until the release process is completely decoupled from the Kyma releases. It will be possible to introduce multiple simplifications at that time.

**Comment by janmedrek** [comment]
Stopping the development according to: https://github.com/kyma-project/community/issues/872
