### ISSUE TITLE
Force flag for kyma delete module command.

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/cli#1812]
**Description**

Implement a force flag for the `kyma delete module` command. With the force flag enabled all resources managed by the module should be deleted before the module operator is uninstalled.

**Related issues**
- https://github.com/kyma-project/kyma/issues/18318
- https://github.com/kyma-project/cli/issues/1806

**Comment by janmedrek** [comment]
Blocked by: https://github.com/kyma-project/lifecycle-manager/issues/963

Until we have a clear contract on what resources should be removed we cannot really proceed with this task.

**Comment by janmedrek** [comment]
Stopping the development according to: https://github.com/kyma-project/community/issues/872
