### ISSUE TITLE
Enforce proper semver during the module build process

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/cli#1854]
**Description**

CLI should fail if the version of the module (template) or the module artefacts (docker images, manifests etc.) does not follow the semantic versioning guidelines.

**Reasons**

We want to have unified versioning across modules and their components.

**Acceptance Criteria**

- [ ] Build Module command requires proper semver in both the module template and the module artefacts
- [ ] If the provided version is incorrect the command should fail

**Comment by a-thaler** [comment]
What is with the development phase? I want to create a template out of a PR version to test/validate, do I must use a suffixed semVer version already?

**Comment by janmedrek** [comment]
We have decided to extract the module creation logic from the CLI, it should be implemented in the module submission pipeline
