### ISSUE TITLE
Enable and configure `importas` linter

### ISSUE THREAD

**Issue by jeremyharisch** [kyma-project/cli#1867]
**Description**
enable and configure `importas` linter as in [Lifecycle-Manager](https://github.com/kyma-project/lifecycle-manager/blob/main/.golangci.yaml#L55).

**ACs**
- [ ] enable `importas` linter
- [ ] Configure `importas` linter same as in Lifecycle-Manager

**Comment by janmedrek** [comment]
Stopping the development according to: https://github.com/kyma-project/community/issues/872
