### ISSUE TITLE
Remove Istio leftovers

### ISSUE THREAD

**Issue by triffer** [kyma-project/cli#1874]
**Description**
After the rollout of the Istio module, we are removing the Istio component from the Kyma charts. If there are still leftovers in the CLI, these should also be removed.

**Attachments**
- https://github.com/kyma-project/kyma/pull/18453

**Comment by janmedrek** [comment]
@triffer is there any confirmed Istio usage in the CLI? Or did you just create the issue proactively?

**Comment by triffer** [comment]
We created the issue to inform you about the removal of Istio component, so you can double check CLI code. This issue was also created before the PR https://github.com/kyma-project/cli/pull/1876 . So it might not be relevant any longer.

**Comment by lindnerby** [comment]
Closing this since dependency has been removed with mentioned PR.
