### ISSUE TITLE
2.20.1 tag archive checksum mismatch

### ISSUE THREAD

**Issue by samford** [kyma-project/cli#1888]
Hi, I'm a maintainer for the Homebrew package manager. I noticed that the checksum for the `2.20.1` tag archive changed between when it was tagged and we updated the formula on 2023-12-14 (https://github.com/Homebrew/homebrew-core/pull/157340) and now. I was checking versions yesterday and noticed that the latest reported version was 2.20.0 (instead of 2.20.1), so it seems like the tag may have been removed and recreated before the 2.20.1 release was created.

I just wanted to confirm that this checksum change is expected and that everything is good before I create a PR to update the SHA256 in the formula.

If there were any notable changes in the interim time, we will need to repackage it on our end. It seems that the only change in that time period was https://github.com/kyma-project/cli/commit/73bea7c70720927c5d11977817531bfe4756cf4d, which updates the version of kyma-incubator/reconciler in `go.mod`.

-----

I will also add a `livecheck` block to the formula to ensure that we identify version information from the latest GitHub release instead of Git tags, as it appears that you use releases to indicate when a version is actually released. This should reduce the chance of us running into this issue again in the future (e.g., if you regularly re-tag versions before creating the GitHub release), though it would still be an issue if the tag changes after a release is created.

**Comment by ruanxin** [comment]
Hi @samford ,

thanks for notifying us this issue! Yes, we have the issue that previously released version `2.20.1` to homebrew has not been released to github, in the meanwhile, we have a [hotfix](https://github.com/kyma-project/cli/commit/73bea7c70720927c5d11977817531bfe4756cf4d) (that bump reconciler dependencies )get merged, so we decided to remove the tag and release `2.20.1` again in github, but didn't pay attention that this will bring checksum mismatch in homebrew release.

For this repackage task, is anything expected to be done on our side? Feel free let us know, and thanks again for taking care this issue👍

**Comment by samford** [comment]
Thanks for confirming. I will move forward with updating the checksum in the formula.

As long as you don't re-tag a version after the GitHub release is created, this shouldn't be an issue in the future. We generally discourage re-tagging in general since it can lead to checksum issues like this but I'll be updating the formula's `livecheck` block to check GitHub releases instead of tags, so we shouldn't run into this particular issue again since the version was re-tagged before the GitHub release was created.
