### ISSUE TITLE
checksum mismatch for 2.20.1 release

### ISSUE THREAD

**Issue by chenrui333** [kyma-project/cli#1892]
👋 it looks like 2.20.1 release got re-created, raise this issue to confirm it. Thanks! (would be nice to do roll forward rather than re-creating a new release though 🙏 )

relates to https://github.com/Homebrew/homebrew-core/pull/157653

**Comment by samford** [comment]
This was already confirmed in https://github.com/kyma-project/cli/issues/1888#issuecomment-1862406170

**Comment by ruanxin** [comment]
thanks for confirming @samford 👍 , sorry guys for this inconvenience.
