### ISSUE TITLE
Upgrade the default K8S version to 1.28

### ISSUE THREAD

**Issue by zhoujing2022** [kyma-project/cli#1936]
**Description**

The default K8S version should be bumped to 1.28.

This change needs to be aligned with the rest of the tasks: https://github.com/kyma-project/kyma/issues/18558
Current estimate for the Kyma readiness is 10.Apr.2024

Acceptance Criterias

- [ ]  Default K8S version in the CLI is 1.28

**Comment by janmedrek** [comment]
I believe this one can be closed as CLI will not be used to provision K8S clusters anymore.
