### ISSUE TITLE
Update CLI documentation with information on available flags

### ISSUE THREAD

**Issue by tomekpapiernik** [kyma-project/cli#194]
**Description**

Please describe all available flags in the CLI readme. I don't really know how many there are because there's no way for me to know if don't dig into the source code. I learned from Slack that you can use `-r` to specify a revision, but I can't learn about any limitations this flag has because it's not documented. In the same Slack conversation `--override` and `--config` are mentioned. 

**Reasons**

The users should be aware of all flags available in the CLI - some of them are very useful. 

**Attachments**

![image](https://user-images.githubusercontent.com/29116492/62428561-6ba0dc80-b703-11e9-9d13-756d9a9acfce.png)

**Comment by bszwarc** [comment]
The aim is to have a separate document for each command (including flags) like this one: https://github.com/kyma-project/cli/blob/master/docs/install.md. However, you are right that flags should at least be mentioned in the README file.

**Comment by bszwarc** [comment]
This task was addressed by this PR: https://github.com/kyma-project/cli/pull/231
