### ISSUE TITLE
Introduce an abstraction layer for the OCM library

### ISSUE THREAD

**Issue by c-pius** [kyma-project/cli#1941]
**Description**

For the new CLI, we want to create an abstraction layer shielding the OCM dependency. The abstraction shall provide an API focussing on the functionality we need and internally delegate to the OCM library.

**Reasons**

This will reduce our code's coupling to the OCM library and make it easier in the future to cope with (breaking) changes within the library.

**Attachments**

**Comment by janmedrek** [comment]
Moving to the new repo: https://github.com/kyma-project/modulectl/issues/6
