### ISSUE TITLE
Remove alpha sign and verify command

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/cli#1943]
**Description**

The `alpha sign` and `alpha verify` command are designed to do signatures for module template in order to provide trust for module submission. However, the current kcp module submission pipeline is fully controlled by the internal team, there is no need to support this signature behavior.

**AC**
- [ ] remove `alpha sign` and `alpha verify` command and related code completely.

**Comment by janmedrek** [comment]
Hey @ruanxin, since we will be moving away from the CLI repository let's do this one as a part of the migration: https://github.com/kyma-project/lifecycle-manager/issues/1274

I will close this ticket, I have updated the description of the epic accordingly.
