### ISSUE TITLE
Release 2.20.3 and publish the binary

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/cli#1945]
**Description**

A version for the 2.x.x should be released, including all the recent commits in the repository. To simplify the migration we should also publish a binary (like the [unstable one](https://github.com/kyma-project/cli?tab=readme-ov-file#kyma-cli-binaries)) so that teams using the unstable version can reference the specific version (instead of relying on latest).

**Reasons**

The next version of the CLI will introduce breaking changes, we want to enable teams to pin the specific version.

**Acceptance Criteria**
- [x] New version released (release notes contain binary link)
- [x] Manually publish the binary (`https://storage.googleapis.com/kyma-cli`)

**Comment by nesmabadr** [comment]
The binaries are published to https://storage.googleapis.com/kyma-cli-stable
