### ISSUE TITLE
Ensure CIS  instance (`local` plan) for managed kyma provisioning

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/cli#1962]
**Description**
Kyma CLI should determine which CIS plan is used in the context and :
 - if `local` plan is given, than no need to ensure enything (use it to instanciate Kyma Environment in next steps )
 - if `central` plan is given, than use it to ensure a new CIS instance with `local` plan in the subaccount

At the end of the day `local` plan miust be used to instantiate kyma.

**Related**
Part-of #1942

**Comment by Cortey** [comment]
If a user uses CLI with `central-cis` credentials we're able to verify that he uses invalid credentials and give his subaccount entitlement to be able to create `local-cis` but we cannot provision him a new instance using the `central-cis` due to its scope being insufficient

**Comment by kwiatekus** [comment]
We should in such case respond with insufficient scope error message.
User should recognize what to do in next steps (manually provision CIS instance that is local to his subaccount)

**Comment by kwiatekus** [comment]
Error handling issue #1992
