### ISSUE TITLE
Provide Linux installation option

### ISSUE THREAD

**Issue by zongqichen** [kyma-project/cli#1975]
**Description**
Hi Colleagues, I would suggest that we provide the Linux installation instead of building from source.

**Reasons**
We already have installations on Windows and MacOS, Linux I guess is popular in development as well.  Providing Linux installation on Linux could be convenient for Linux developers as well.

**Comment by janmedrek** [comment]
Hey @zongqichen, we've recently changed the direction in which the Kyma CLI will be developed. If you want to have more info then please have a look [at this discussion](https://github.com/kyma-project/community/issues/872).

As for the last release - Linux binaries are published, you can do:
```
curl -Lo kyma https://storage.googleapis.com/kyma-cli-unstable/kyma-linux # or kyma-linux-arm
chmod +x kyma
```

Perhaps we can consider registering a new apt package for this, but this is something I would rather leave to @kwiatekus as he will be driving the new implementation of Kyma CLI.

**Comment by zongqichen** [comment]
Hi @janmedrek,

thank you for your explanation. I'm new to kyma and just follow this [repo](https://github.com/kyma-incubator/compass/blob/main/README.md)to install all dependencies. Now I see the situation of kyma. If no more discussion, I will close it.
