### ISSUE TITLE
Deprecate selected commands in kyma CLI

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/cli#2051]
**Description**

Warn users that kyma cli v2 is EOL
All current commands are deprecated and new v3 commands will be developed within `alpha` command group
Link [decision](https://github.com/kyma-project/community/issues/872) 

 - Publish Whats new 
 - Introduce a warning at the beginning of readme.md
 - Show warning message in the terminal when any kyma CLI  command is executed
 
**Reasons**
Commands targeting  development use cases will be removed from CLI. Those  targeting end-users will undergo necessary adjustment to modular kyma. Those which bring little value comparing to maintanance cost will eventually be removed.
https://github.com/kyma-project/community/issues/872

**Comment by pPrecel** [comment]
[Here](https://github.com/kyma-project/community/blob/main/docs/guidelines/releases-guidelines/03-kyma-cli-release-process.md) is the article how to release old kyma-cli
