### ISSUE TITLE
Installing release "master" can ends up with ImagePullBackOff for kyma-installer

### ISSUE THREAD

**Issue by aszecowka** [kyma-project/cli#206]
In job `pre-master-compass-integration` we install kyma from release "master"

`kyma install -o $INSTALLER_CR_PATH --release master`
This cause that `installInstallerFromRelease` is executed, which calls `getMasterHash` method, which is implemented in the following way:
```
func (cmd *command) getMasterHash() (string, error) {
	ctx, timeoutF := context.WithTimeout(context.Background(), 1*time.Minute)
	defer timeoutF()
	r, err := git.CloneContext(ctx, memory.NewStorage(), nil,
		&git.CloneOptions{
			Depth: 1,
			URL:   "https://github.com/kyma-project/kyma",
		})
	if err != nil {
		return "", err
	}
	h, err := r.Head()
	if err != nil {
		return "", err
	}

	return h.Hash().String()[:8], nil
}
```

Such an approach can cause a problem if job `post-master-kyma-development-artifacts` fails to build kyma-installer image for the recent commit. This happened recently: https://storage.googleapis.com/kyma-prow-logs/logs/post-master-kyma-development-artifacts/1162292035089076225/build-log.txt
where there was a problem with communication with github.

-----

Suggested solution by @clebs to be implemented:

- Check if the installer image for the current master exists.
- If it does not exist for whatever reason, the previous hash will be taken and the user will be informed with a warning that the CLI resorted to the previous master image.
- There will be a depth of 3 commit hashes to try to find the image, if none is found the CLI will abort installation.

**Comment by igor-karpukhin** [comment]
@aszecowka, yes, CLI will fail to install the latest master if it can't access the official kyma repository. Is that a bug? I mean, if there is no access to an external resource that is required it should fail.

**Comment by clebs** [comment]
Hi @aszecowka,
the proposed solution for this issue will be:
- Check if the installer image for the current master exists.
- If it does not exist for whatever reason, the previous hash will be taken and the user will be informed with a warning that the CLI resorted to the previous master image.
- There will be a depth of 3 commit hashes to try to find the image, if none is found the CLI will abort installation.

**Comment by a-thaler** [comment]
Figuring out next revision in history seems possible seeing the code in the description.
More relevant is how to check if the related docker image exist or not. As this needs to happen pro-active. Any idea how to do it with GCR, best without using a docker client and (must) in an anonymous way?

**Comment by aszecowka** [comment]
@a-thaler If a user wants to install kyma from the master, we can read current commit ID, but also previous commit IDs. As you can see in `test-infra/prow/scripts/build-kyma-development-artifacts.sh`, the following steps are executed:
- build kyma-operator
- build kyma-installer
- copy artifacts to a proper bucket on GCP

Maybe the easiest way is to check if the given director in GCS exists?

**Comment by a-thaler** [comment]
As it is the last step, we can just check for one of the typical artifacts. However a bit fragile as the change of the upload structure will break existing clients out there.
So at least we must document it inside the job.

I figured out the anonymous URL which we could use
`https://storage.googleapis.com/kyma-development-artifacts/master-00a06f01/kyma-installer-cluster.yaml`
Doing a HEAD request on existing resource indeed returns a 200, otherwise 404
