### ISSUE TITLE
Automate provisioning SAP Cloud Identity Authentication service instance

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/cli#2114]
**Description**

Prototype a kyma cli command that configures SAP IAS tenant as Identity Provider for Kyma.
This includes:
 - provisioning and binding a SAP Identity services (IAS) via btp-operator 
 - establishing trust between the IAS service instance and btp subaccount (how ? in automated way)
 And not includes:
 - updating kyma instance with oidc params (separate command to uopdate kyma instance)

**Reasons**

Provisioning and configuring SAP IAS Service instance as kyma identity provider is complex, multi-stage process that when not automated, is definitely error-prone.

Having a cli command that takes off the burden is very much expected.

**Attachments**

Gist [example](https://community.sap.com/t5/technology-blogs-by-sap/configure-custom-sap-ias-tenant-with-sap-btp-kyma-runtime-environment/ba-p/13676954) from @ptesny explaining the process (with screenshots) and with automation suggestions inline in the text

**Comment by ptesny** [comment]
There is another gist of mine with the BTP CLI this time....
[Jumpstart kymaruntime environment from SAP BTP trial.](https://gist.github.com/ptesny/aa8bc30ce043e1e11c145fe15278db62)

**Comment by ptesny** [comment]
This can be fully managed with the help of the terraform scripts.....

1. https://github.com/ptesny/btp-automation/blob/main/btp-context/runtime-context/modules/kyma-runtime/bootstrap-custom-idp-k8s.tf
2. https://github.com/ptesny/btp-automation/blob/main/btp-context/runtime-context/modules/kyma-runtime/bootstrap-custom-idp-bot.tf

**Comment by kwiatekus** [comment]
closing as there is terraform alternative.
terraform module for kyma is doing [that](https://github.com/kyma-project/terraform-module/blob/main/main.tf#L99-L147)
