### ISSUE TITLE
Redesign CLI provision command based on Hydroform

### ISSUE THREAD

**Issue by clebs** [kyma-project/cli#220]
**Description**
Redesign the provision command in the Kyma CLI to accommodate the newly supported platforms and parameters.

**Acceptance**
- The new provisioning command supports all needed options for Hydroform.
- It is possible to create all supported clusters via CLI.
- New command is documented.

**Comment by clebs** [comment]
Currently this issue is blocked by https://github.com/kyma-incubator/octopus/issues/35

**Comment by bszwarc** [comment]
Docu follow-up on this one:

#5787 GKE installation docs improvements
#220 Check the provision command, generate and adjust. Improve the readme
