### ISSUE TITLE
Allow enabling managed modules via kyma CLI

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/cli#2274]
**Description**

User of managed kyma runtime should be able to:
 - enable managed module (with custom module CR) 
 - enable managed module (with default module CR)
 - disable managed module

**Reason**
Possibility to toggle modules on/off via cli would simplify implementing automation scenarios for kyma users

**Related**
Part of https://github.com/kyma-project/cli/issues/2251

**Ideas**
`kyma alpha module enable serverless` - enables serverlss operator, but serverless CR is not created
`kyma alpha module enable serverless --defult-config` - enables serverlss operator, with default serverless CR
`kyma alpha module enable serverless --config {path to serverlss CR}` - enables serverlss operator, with custom serverless CR
`kyma alpha module disable serverless` - removes serverless CR (manually if `CustomResourcePolicy` is set to false) and operator

**Comment by kwiatekus** [comment]
Should we rename `enable/disable` commands to `add/delete` ?
I.e 
`kyma alpha module add template-operator --default-cr`
rather than
`kyma alpha module enable template-operator --default-cr`

**Comment by pbochynski** [comment]
It was discussed when module management was introduced in Kyma Dashboard. Our UX experts recommended us to use add/delete for module management. The same commands should be used in the CLI, so add/delete is the right choice.
