### ISSUE TITLE
Use helm charts as template for apps pushed via CLI

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/cli#2289]
**Description**

Kyma CLI `app push` command should use the [helm chart](https://github.tools.sap/unified-runtime/web-application) that is recommended for developers to use when creating apps for kyma. 
Review `kyma alpha app push` options to make them reflect helm chart values.

**Reasons**

Customers are encouraged to use those [helm charts](https://github.tools.sap/unified-runtime/web-application) when templating application manifests. Those templates provide meaningful defaults leaving user to focuses on the essentials.
It is desired, for kyma-cli generated apps (via `app push` command) to introduce the same default configuration.

**Attachments**
https://github.tools.sap/unified-runtime/web-application
https://pages.github.tools.sap/unified-runtime/docs/building-blocks/unified-build-and-deploy/helm-charts

**Comment by kwiatekus** [comment]
Double check if the value introduced is worth it, taking into account the overhead is added by
 - using helm client in kyma cli.
 - maintaining both options of creating resources: simple and via helm

**Comment by pbochynski** [comment]
Helm charts should be optional. For beginners, it can be difficult to review all the templates and understand what is actually deployed to Kubernetes. Applying best practices and [recommendations](https://github.tools.sap/unified-runtime/web-application/blob/main/docs/README.md#recommendations) is also possible without helm charts. In my opinion helm charts should remain optional.

**Comment by kwiatekus** [comment]
Thanks @pbochynski. We will not introduce it at this moment.
