### ISSUE TITLE
Local installation should respect the --domain flag

### ISSUE THREAD

**Issue by clebs** [kyma-project/cli#234]
**Description**
Currently the `--domain` flag is ignored by the `kyma install` command if it is installing kyma locally.
The behaviour should be the same as when installing on a remote cluster, the `--domain` flag should be taken into account when installing kyma locally and the user provided domain should be used everywhere instead of `kyma.local`.

**Reasons**
Users should be able to change the default local domain (`kyma.local`) to anything and it should work the same way as with `kyma.local`

**Comment by suleymanakbas91** [comment]
Fixed by #449.

**Comment by a-thaler** [comment]
I tried to install local with a custom domain but failed:

1. To use --domain you also need to set --tlsKey and --tlsCert. That flags expect the values as a base64 encoded single-line string. That is not guessable at all and I wasted a lot of time to figure it out. Please improve at least the inline docu to make that transparent.

2. The three flags result in a new configmap "owndomain-overrides" with proper keys and values, as expected. Unfortunately, the configuration used by default for the local setup (https://github.com/kyma-project/kyma/blob/master/installation/resources/installer-config-local.yaml.tpl) defines the default values for the three flags in a configmap called "installation-config-overrides". With that, two versions of the same properties are active, not sure what the result will be. Either remove the existing values as part of the patch or change to the default configmap using the same approach as for the password logic (which works great)

3. The minikubeIP is not configured. Checking the CLI sources, the "kyma.local" domain is hardcoded to figure out local usage, the if block will not get active for a custom domain: https://github.com/kyma-project/cli/blob/431add706900a2d0e65cf19e510e72b0646f1c6c/pkg/installation/installation.go#L137 I think that local domain check is not needed, if isLocal configure minikubeIP. If custom domain, configure it.
