### ISSUE TITLE
Add xip integration

### ISSUE THREAD

**Issue by sjanota** [kyma-project/cli#24]
Kyma will be switching to xip DNS as default: https://github.com/kyma-project/kyma/issues/2563

1. We need to keep an eye on that to find if there is something to be done during installation.
2. If there is we need to add it.
3. This change is not applicable for local installation so maybe we're not there yet.

**Comment by sjanota** [comment]
This is not required until we have support for some cloud provider like GKE or AKS

**Comment by a-thaler** [comment]
Will close the issue and address it when introducing support for non-local installations
