### ISSUE TITLE
Decouple install functionality from command

### ISSUE THREAD

**Issue by clebs** [kyma-project/cli#245]
**Description**
Right now the install command contains all the logic to install Kyma. It would be very beneficial to extract and encapsulate that logic into a standalone package for reusability.

**Reasons**
- Make the CLI more modular
- Separate command and terminal logic from Kyma specific logic
- Allow others to import the package and use it too.

**Comment by a-thaler** [comment]
Please assure that the new API was reviewed by the compass team before merge
