### ISSUE TITLE
Restarting minikube throws an error

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/cli#248]
**Description**
If you provision minikube without deleting the existing machine it fails with the error:
```
X Creating cluster info ConfigMap
Error: configmaps "kyma-cluster-info" already exists
```

**Expected result**
I wold like to see success message.

**Actual result**

```
X Creating cluster info ConfigMap
Error: configmaps "kyma-cluster-info" already exists
```

**Steps to reproduce**

```
kyma provision minikube
kyma install --source local --src-path ./
minikube stop
kyma provision minikube
```
Answer no for the question: "Do you want to remove the existing Minikube cluster?"

**Comment by a-thaler** [comment]
Should not fail for sure. I even would say it should update the configmap with the potential new settings if exist

**Comment by a-thaler** [comment]
In case of existence of either owndomain-overrides or kyma-cluster-info it now prints: "ConfigMap already exists". No further context gets provided

That is a CLI and every line printed to the console needs to be meaningful and useful for the user. Please re-think if you should inform the user at all (maybe in verbose level?) and if yes if all needed info is provided
