### ISSUE TITLE
CLI does not install Kyma from master

### ISSUE THREAD

**Issue by Szymongib** [kyma-project/cli#249]
**Description**

Due to changes to the path of `kyma-installer` image (https://github.com/kyma-project/kyma/commit/d8eab8c07ad6ac1fcde244ec2c1f6371a0f43ad6), the CLI creates image name that does not exist and as a result, the installation is stuck on `Deploying Kyma Installer`, which is in `ImagePullBackOf` state.

**Expected result**

CLI is able to install Kyma from the master.

**Actual result**

Installation stuck on `Deploying Kyma Installer`.

**Comment by a-thaler** [comment]
Fixed by @strekm
