### ISSUE TITLE
Use requirements file distributed with Kyma release

### ISSUE THREAD

**Issue by sjanota** [kyma-project/cli#25]
Kyma 0.8 will be distributed with file which contains supported versions of required tools: https://github.com/kyma-project/kyma/issues/2644. We could use this to dynamically check if requirements are met. Two checks should be in place:

1. Check if appropriate versions of tools are installed on OS.
2. Check if those versions are supported by kyma-cli.

**Comment by a-thaler** [comment]
In mid term we will use binary dependencies only for cloud provider tooling which is optional anyway (dependent on what command you are executing). Kyma should not have dependencies to the tooling at all (in long term) but only the CLI should define the supported versions. So I like to skip this story.
