### ISSUE TITLE
Update homebrew formula on every CLI release

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/cli#252]
**Description**
Finally the CLI has its own homebrew formula: https://formulae.brew.sh/formula/kyma-cli

Now we need to assure that it gets updated on every release. For that, please target automation as much as possible and document all manual steps in the release process documents.

Requirements:
- when following the release process as documented, a new CLI version is always available in homebrew as well (at least the homebrew publishing process is triggered and a responsible person is assigned)
- remove/deprecate the old formula
- update the CLI readme on how to install the CLI

**Reasons**
User expects always up-to-date homebrew formula

**Attachments**
- release document: https://github.com/kyma-project/community/blob/master/guidelines/releases-guidelines/03-kyma-cli-release-process.md
- gorelease support: https://goreleaser.com/customization/#Homebrew

**Comment by clebs** [comment]
Added a new step on the CLI release guidelines linking to the Homebrew guide on how to update a formula's version, together with an example from one of our previous PRs.

Also tested the process by updating the homebrew formula from `1.11.0` to `1.11.1`.
