### ISSUE TITLE
Use upper case for default values when asking user for confirmation

### ISSUE THREAD

**Issue by nachtmaar** [kyma-project/cli#255]
**Description**

When asking the user to confirm/decline an operation, usually the default value is written in upper case letters. Let's apply this standard to the CLI.

https://stackoverflow.com/questions/7803728/standard-format-for-yes-no-questions-in-the-terminal

Example:
```shell
$ kyma provision minikube
...
? Do you want to remove the existing Minikube cluster? Type [y/n]:
```

https://stackoverflow.com/questions/7803728/standard-format-for-yes-no-questions-in-the-terminal

**Expected result**

Example:
```shell
$ kyma provision minikube
...
? Do you want to remove the existing Minikube cluster? Type [Y/n]:
```

**Actual result**

**Steps to reproduce**

**Troubleshooting**

**Comment by jbleduigou** [comment]
Looking into it

**Comment by clebs** [comment]
This issue was already foxed by #256. It stayed open by mistake, closing
