### ISSUE TITLE
Expand the Kyma CLI documentation

### ISSUE THREAD

**Issue by bszwarc** [kyma-project/cli#278]
**Description**

So far we have auto-generated documentation stored here: https://github.com/kyma-project/cli/tree/master/docs/gen-docs. This and the README is the only documentation we have. We need some more documentation describing Kyma CLI that later on can be rendered on the website.

What should be done:
- move the docs into the `cli/docs` directory
- remove the OWNERS file from the docs (remove completely? move somewhere?)
- add an overview of CLI
- add CLI architecture doc 
- add some use cases? FAQ? 

**Reasons**

Kyma CLI is gaining interest. We would like our CLI documentation hosted on the website as a separate section, but for that, we need something more than just the generated commands and the README.md file.

**Comment by bszwarc** [comment]
This is still valid

**Comment by a-thaler** [comment]
Duplicated by https://github.com/kyma-project/cli/issues/279
