### ISSUE TITLE
Installing Kyma from source local does not work

### ISSUE THREAD

**Issue by aszecowka** [kyma-project/cli#283]
**Steps to reproduce**
1. Fetch Kyma CLI from master branch
2. Execute `make build-darwin`
3. Move binary to your path: `./bin/kyma-darwin /usr/local/bin/kyma`
4. Provision minikube: `kyma provision minikube`
5.  Install Kyma from local sources: `kyma install --source local`

Installation hangs on:
` Deploying Kyma Installer`

Status of `kyma-installer` namespace is the following:
```
NAME                              READY   STATUS              RESTARTS   AGE
helm-certs-job-5ds26              0/1     CrashLoopBackOff    5          5m43s
kyma-installer-6c479467f6-64xjr   0/1     ContainerCreating   0          5m43s
```
Helm certs job fails because:
```"tiller-secret" not found```

When I checked how Tiller is installed, I noticed that instead of using my local `tiller.yaml` this file is used:
`https://raw.githubusercontent.com/kyma-project/kyma/latest//installation/resources/tiller.yaml`

As you can see, `latest` version is used, which is really old. In this version, tiller is installed with disabled TLS and probably because of that `tiller-secret` does not exist.

**Comment by a-thaler** [comment]
Solved by the linked PR
