### ISSUE TITLE
Failures of `rel-kyma-cli` job

### ISSUE THREAD

**Issue by aszecowka** [kyma-project/cli#293]
Doing release 1.7 we encountered many problems with releasing CLI, jobs failed with such message:

```
release failed after 0.89s error=git is currently in a dirty state, please check in your pipeline what can be changing the following files:
 M go.mod
 ```

Presubmit jobs should prevent such a situation.

**Comment by clebs** [comment]
Hi @aszecowka,
we will check on the presubmit jobs what `go mod tidy` returns and fail if there are changes on the .mod files.

**Comment by suleymanakbas91** [comment]
I realized this was because of `go generate` which altered the go.mod file.

**Comment by derberg** [comment]
@clebs @suleymanakbas91 this one is fixed by linked PR or is there still something more to do?

**Comment by suleymanakbas91** [comment]
@derberg it is fixed by the PR. It is on to accept state waiting for Andreas to accept and close the ticket.
