### ISSUE TITLE
Add test support on base of Octopus

### ISSUE THREAD

**Issue by sjanota** [kyma-project/cli#32]
**Description**
Introduce Kyma test functionality based on the Kyma test suite and the octopus framework. A `testing.sh` script should not be required anymore as you can run a suite with one command. And figure out the problem area with one command. That commands are easily understandable by just reading the in-line help.

**Reason**
Executing the kyma tests got improved a lot by having it based on [Octopus](https://github.com/kyma-incubator/octopus). Still, it can be quite inconvenient to create the resources and figure out the status of a test execution in comparison to execute a simple command. From devX perspective, it should be a trivial task to execute the kyma test suite and investigate the problems.

**Details**
Overall goal is to remove the `testing.sh` in kyma repo and instead use the CLI commands.

The proposal is to have following commands:

1. `kyma test run <tests>` - creates new TestSuite
    Parameters:
    * `tests` - comma-separated list of names, `selector.matchNames` in TestSuite, empty list selects all tests

    Options:
    * `-n/--name` - name of the test suite, generated by default
    * `--timeout` - `suiteTimeout` in TestSuite
    * `--concurrency` - `concurrency` in TestSuite
    * `-l/--labels` - comma-separated list of labels, `selector.matchLabels` in TestSuite
    * `-c/--count` - number of times suite should be executed, `count` in TestSuite
    * `--max-retries` - allowed number of retries per test, `maxRetries` in TestSuite
    * `-w/--watch` - watch status of TestSuite until completion
    * `--delete` - remove TestSuite after successful completion

2. `kyma test delete <name> <name> ..` - deletes TestSuite and all its resources
    Parameters:
    * `name` - mandatory name of the test suite to delete, can be provided multiple times

    Options:
   * none

3. `kyma test status <name> <name>` - prints nicely formatted status of TestSuite, prints command instructions to easily re-run a suite
    Parameters:
    * `name` - optional name of the test suite to describe, can be provided multiple times

    Options:
    * `-w/--watch` - watch status of TestSuite until completion
    * `-o json|yaml` - prints raw testSuite resource in specified format

4. `kyma test logs [<name>]` - print failing logs from test suite
    Parameters:
    * `name` - optional name of the test suite to retrieve logs from, default is latest started suite

    Options:
    * `-f/--follow` - follow logs
    * `--test-status` - selects logs of pods in status "Running, Failed, Success"
    * `--definitions` - selects the pods related to the definitions in the test suite to show logs of 

5. `kyma test list` - print all created suites with their statuses
    Parameters:
    * none

    Options:
    * none

6. `kyma test definitions` - print all available TestDefinitions
    Parameters:
    * none

    Options:
    * none

**Example Usage**

With the definition above `testing.sh` would become something like this:
```bash
echo "----------------------------"
echo "- Testing Kyma..."
echo "----------------------------"

kyma test run --name kyma-suite --timeout 30m --watch
testCheckCore=$?

kyma test status kyma-suite
kyma test logs kyma-suite
kyma test clean kyma-suite

exit ${testCheckCore} 
```

**Comment by sjanota** [comment]
With the definition above `testing.sh` would become something like this:
```bash
function checkAndCleanupTest() {
    local suite=$1
    local failedTests=$(kyma suite status "$suite" --status failed,error | cut -f 1 -d ' ')
    for t in ${failedTests}; do
        log "Images with tag latest are not allowed. Checking..." nc bold
        kyma suite logs "$t"
        echo ""
    done

    kyma suite cleanup "$suite"
}

echo "----------------------------"
echo "- Testing Kyma..."
echo "----------------------------"

kyma suite create kyma-suite -t 30m -w
testCheckCore=$?

checkAndCleanupTest kyma-suite

printImagesWithLatestTag
latestTagsErr=$?

if [ ${latestTagsErr} -ne 0 ] || [ ${testCheckCore} -ne 0 ] 
then
    exit 1
else
    exit 0
fi
```

**Comment by a-thaler** [comment]
Sounds great :)
I'm wondering if the "suite" in "kyma test suite" can be removed as it is used in all commands.
When first reading your idea, I was wondering under which command the execution will be done. Later I realized that "create" will cover execution.... maybe we can name it "run"? The collection of test is already existing/defined, right? we are talking only about execution of them.

**Comment by sjanota** [comment]
1. I was thinking about `kyma test definition list` to list all available tests that can be run within suite. Then the `suite` is meaningful.

2. Yes, the collection of tests exists. We are creating a suite to pick some of them and execute. In a way it is similar to `docker run` which creates the container and starts it in one go. On the other hand its k8s; you don't need to explicitly `start` deployment, you just create it.

**Comment by a-thaler** [comment]
I get your point, create is fine.
About the redundant "suite", do you think there will be more about a test definition than listing all with labels? Maybe it should be just another subcommand
kyma test create - creates test suite
kyma test list - lists test suites
kyma test cases - lists test definitions

**Comment by sjanota** [comment]
Hmmm, actually it makes sense at first glance, but need to think a little longer.

**Comment by sjanota** [comment]
@a-thaler I modified my proposal to reflect your comment. Do you think it's ok now?

**Comment by a-thaler** [comment]
yes, I like it :)

**Comment by kfurgol** [comment]
@a-thaler Are there plans on implementing the support? Because for now, in most Kyma charts there are no helm test hook annotations, so the `kyma test` command gives us a false positive result.

**Comment by a-thaler** [comment]
we removed the test command for the next release 1.2 to not give wrong promises on test execution and also getting rid of the helm dependency. With release 1.3 we will add revamped test command as described in this ticket. That is the plan

**Comment by a-thaler** [comment]
Current kyma test functionality got removed for now to avoid mismatch in test execution with old and new approach, see https://github.com/kyma-project/cli/issues/101
Please remember to add preconditions as outlined in this PR (https://github.com/kyma-project/cli/pull/100) when implementing the new test approach. TRhe PR was based on old way and with that was not applied.

**Comment by bszwarc** [comment]
I'm putting `area/documentation` label on it since we will have to document the approach in our README for kyma CLI.

**Comment by a-thaler** [comment]
For the missing things dedicated tickets are created, will close it
