### ISSUE TITLE
Kyma CLI should validate input params like --override

### ISSUE THREAD

**Issue by dbadura** [kyma-project/cli#333]
**Description**
Currently Kyma CLI do not check if file passed to `--override` param exists.

**Expected result**
Kyma CLI should fail with message indicating that file targeting by `--override` param, not exist or is not valid, before doing any installation.
Kyma CLI before installation any components should print all `override` configuration files which will be applied later.

**Actual result**
Kyma install all components without indicating that `override` file wasn't read.

**Steps to reproduce**
run 
`kyma install -o something`

**Troubleshooting**

**Comment by a-thaler** [comment]
Hi @dbadura, thanks for the feedback, I agree that a check needs to be added and overall transparency on what is happening should be improved

**Comment by a-thaler** [comment]
The error message in case an override is present already is wrong and misleading, could you please fix it as well.

**Comment by a-thaler** [comment]
I was wrong, all is fine
