### ISSUE TITLE
Installation from local sources to a remote cluster

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/cli#334]
**Description**
An installation from local sources is currently supported lof a local installation only. A Kyma installation from local sources need to build the kyma-installer docker image and use that one instead of the original one. At the moment the image gets build from local sources using the minikube docker agent, having the image immediately available in the local cluster. That flow does not work for any remote cluster.

Action:
- Use the current docker agent to build the image
- Make the docker repository/tag configurable
- Push the image
- Adjust kyma-installer yaml to use the pushed image

**Reasons**
Installation from local sources is an important aspect of daily development iteration

**Attachments**

**Comment by suleymanakbas91** [comment]
With https://github.com/kyma-project/cli/pull/507, it is now possible to install Kyma from local sources to a remote cluster. The command looks like: 
```bash
kyma install -s local --docker-username <username> --docker-password <password> --custom-image <image-registry>/<image-name>:<tag>
```

**Comment by a-thaler** [comment]
After the last PR, the command will use the docker credentials of your local docker client to push the installer imager, which is very convenient.
Unfortunately, there is no message indicating that a push is/was happening. As it is a destructive operation potentially overwriting existing images, there should be info in the output

**Comment by suleymanakbas91** [comment]
I improved the logs with #525. New logs look like the following.
In case of successful push:
```
- Cluster type determined
  Installing Kyma from local path: '/Users/xxx/Go/src/github.com/kyma-project/kyma'
  Pushing Docker image: 'dsadasdsa/dasdsadsad:123123'
- Preparations done
- Waiting for installation to start
- install component cluster-essentials
```
In case of permission problems:
```
- Cluster type determined
  Installing Kyma from local path: '/Users/xxx/Go/src/github.com/kyma-project/kyma'
  Pushing Docker image: 'dsadasdsa/dasdsadsad:123123'
X Preparing installation
Error: missing permissions to push Docker image: denied: requested access to the resource is denied
Please run `docker login` to authenticate
```
