### ISSUE TITLE
Commands for local setup

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/cli#335]
**Description**
The "kyma install" command is covering three aspects currently, installation, watch install, setup local infra.
The three parts should be executable independently. For the watch there is https://github.com/kyma-project/cli/issues/41 already, the local setup is missing yet.

The motivation is: my colleague sends me a kubeconfig to an existing remote cluster. In order to debug it I need to setup helm with certificates, install xip certificate, get the password and open the console. All that steps are already implemented in the "kyma install" but not applyable for an existing cluster

As with kyma2 there is no password present anymore, the goal can be summarized to:
Goal: Extract "adding certtificates to local storage" and "adding entries to host file" as dedicated commands to the CLI
Criterias:
- logic will not be called anymore as part of the kyma2 installation
- new commands requires to be executed with elevated permissions (sudo)
- kyma installation requires no sudo password anymore
- if logic is not implemented for windows at least a manual gets printed on what to do

**Reasons**
It is very useful in daily life

**Attachments**

**Comment by chrkl** [comment]
PR #1072 skips adding the hosts entry if already existing and adds support for non-local clusters by using the ingress-gateway IP address
