### ISSUE TITLE
Non-interactive mode for CLI

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/cli#338]
**Description**

There are a lot of situations where the CLI is used in a non-interactive way in automation scripts like ina CI. The Kyma-CLI must be usable in a nice way for such scenarios. For now the --non-interactive flag was used for that. It turned out that the install command is still trying some pretty printing in that mode and even tries to install the Kyma certificates to the local storage (should be required only if someone want to interactively use the browser?)

I suggest to disable any pretty printing in that mode to avoid special characters for coloring.
Furthermore disable any local setup tasks or introduce another flag for automation to supress local setup.

**Expected result**
Log output looks nice and contains no error messages because of missing sudo command or missing user interaction

**Actual result**

```
...
- install component backup-init
- install component logging
- install component jaeger
- install component monitoring
- install component kiali
  Kyma wants to add its root certificate to the trusted certificate store.
! 
Could not import the Kyma certificates. Follow the instructions to import them manually:
-----
1. Download the certificate: kubectl get configmap net-global-overrides -n kyma-installer -o jsonpath='{.data.global\.ingress\.tlsCrt}' | base64 --decode > kyma.crt
2. Rename the certificate file: mv kyma.crt {NEW_CERT_NAME}
3. Copy the certificate to the CA folder: sudo cp {NEW_CERT_NAME} /usr/local/share/ca-certificates/
4. Update the certificate registry: sudo update-ca-certificates
-----
: Executing command 'sudo [cp /tmp/kyma-006030081.crt /usr/local/share/ca-certificates/kyma-*.13.81.249.43.xip.io.crt]' failed with output '' and error message 'exec: "sudo": executable file not found in $PATH'

[0;36mKyma[0m is installed in version:	[0;33;1mmaster-117e418f
[0m[0;36mKyma[0m is running at:		[0;33;1mhttps://api.grdnr-2b8y9m.kyma-prow.shoot.canary.k8s-hana.ondemand.com
[0m[0;36mKyma[0m console:			[0;33;1mhttps://console.13.81.249.43.xip.io
[0m[0;36mKyma[0m admin email:		[0;33;1madmin@kyma.cx
[0m[0;33;1m
[0m
Happy [0;36mKyma[0m-ing! :)
```

**Steps to reproduce**

`kyma install --non-interactive --source latest --timeout 45m`

**Troubleshooting**

**Comment by suleymanakbas91** [comment]
I introduced a `ci` flag for all the ci jobs. Pretty printing should be disabled for `ci` flag, not for `non-interactive`.

**Comment by a-thaler** [comment]
Shouldn't it be a root parameter like verbose as it should be leveraged in all commands, so a CI can just always pass that parameter?

**Comment by suleymanakbas91** [comment]
`ci` is a root parameter, so the jobs can use that.
