### ISSUE TITLE
provision azure command misses details about credentials file

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/cli#345]
**Description**
The provision azure command requires a credentials parameter with a TOML file as input. Unfortunately, it is not mentioned how the file needs to be structured nor an example is provided.
**Expected result**
There is a clear description of how to provide the expected values

**Actual result**
A lot of guessing is needed

**Steps to reproduce**
kyma provision azure -n icke -c /Users/xx/az-huskies.toml -p icke

Now guess what needs to be placed inside the toml file.

**Troubleshooting**
In the dependent hydroform project you will find the answer: https://github.com/kyma-incubator/hydroform/tree/master/provision/examples/azure

**Comment by suleymanakbas91** [comment]
will be solved by https://github.com/kyma-project/cli/pull/358
