### ISSUE TITLE
Rename provision commands to "gke" and "aks"

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/cli#355]
**Description**
There a re multiple ways to create a kubernetes cluster on GCP and Azure. I suggest to be more specific in the command name to have no room for interpretation

```
kyma provision gke
kyma provision aks
kyma provision gardener
```

For gardener, we might even think of sub commands to make it easier to use, like
```
kyma provision gke
kyma provision aks
kyma provision gardener gcp
kyma provision gardener az
kyma provision gardener aws
```
Should be addressed here: https://github.com/kyma-project/cli/issues/441

**Reasons**
Reduce confusion for customers

**Attachments**

**Comment by suleymanakbas91** [comment]
With #446, I renamed the provisioning commands 
- `provision gcp` -> `provision gke`
- `provision azure` -> `provision aks`.
I also introduced the subcommands `gcp`, `az`, and `aws` for `gardener` subcommand with their own defaults.

**Comment by suleymanakbas91** [comment]
I also adapted provision commands used on test-infra to the changes: https://github.com/kyma-project/test-infra/pull/2303
