### ISSUE TITLE
Kyma CLI `--source local` installation fails on remote cluster

### ISSUE THREAD

**Issue by kasiakepka** [kyma-project/cli#394]
**Description**

Kyma CLI local installation (`--source local`) on remote cluster does not work.

Errors we get:
```
kyma install --source local
- Cluster info read
- Configurations validated
  Installing Kyma from local path: '/xxx/go/src/github.com/kyma-project/kyma'
- Installation source checked
/ Validating configurations - Tiller deployed
- Installation files loaded
- Kyma Installer deployed
- Helm configured
- Kyma Installer is installing Kyma
! Get Kyma Sources failed, which may be OK. Will retry later...
  To fetch the error logs from the installer, run: kubectl get installation kyma-installation -o go-template --template='{{- range .status.errorLog }}{{printf "%s:\n %s\n" .component .log}}{{- end}}'
  To fetch the application logs from the installer, run: kubectl logs -n kyma-installer -l name=kyma-installer
- Signal 'interrupt' received from Terminal. Exiting... 
```

Logs of installer indicate that a component tries to get installed which is not bundled into the installer docker image. With that it tries to download it but cannot find it as the installer is not configured for downloads.
```
2020/02/26 08:17:00 Starting operator...
2020/02/26 08:17:00 Git commit hash: 408cb6a606d2915f25499e1bbb53b97fff858499
2020/02/26 08:17:02 ---------------------------
2020/02/26 08:17:02 Get Kyma Sources
2020/02/26 08:17:02 ---------------------------
2020/02/26 08:17:02 Kyma sources not available. Downloading...
2020/02/26 08:17:02 Downloading Kyma, Version: __VERSION__ URL: __URL__
2020/02/26 08:17:03 Bash script error
2020/02/26 08:17:03
2020/02/26 08:17:03 Bash script output
2020/02/26 08:17:03
2020/02/26 08:17:03 Fetch Kyma package error:  Details: exit status 6
2020/02/26 08:17:03 Error during install/update:  Details: exit status 6
```

**Expected result**

Kyma CLI local installation works on remote cluster.

**Actual result**

Kyma CLI local installation (`--source local`) on remote cluster fails.

**Steps to reproduce**

**Troubleshooting**
The challenge is to use a installer image which has the local components bundled. So you must build an image locally and upload it somewhere. That can be done easily by calling in the kyma repo:

```
docker build -t youraccount/kyma-installer:test -f ./tools/kyma-installer/kyma.Dockerfile .
docker push youraccount/kyma-installer:test
```

Then you can either just specify the new image in the source parameter of the CLI call:
```
kyma install --source=youraccount/kyma-installer:test
```

or you change the image to be used in the local `installation/resources/installer.yaml` file.

**Comment by a-thaler** [comment]
That is a missing feature, see https://github.com/kyma-project/cli/issues/334
We should either introduce it or let the command fail

**Comment by suleymanakbas91** [comment]
We will implement it via https://github.com/kyma-project/cli/issues/334.
