### ISSUE TITLE
Idempotent installation process - re-attach

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/cli#403]
**Description**
The current behavior of the install command is not transparent and consistently applied in case it was called already for a cluster.
Expected behavior:
- Naked cluster (no installer namespace, no overrides, no tiller, no installer, no installation CR) -> Start installation with given configuration, local setup
- Cluster with no installation CR but installer namespace, overrides or tiller or installer -> Treated as naked, overrides and tiller and installer will be re-applied, start installation, local setup
- Cluster with installation CR - status ready (no installation started) -  show kyma version, start installation, local setup
- Cluster with installation CR - status inProgress -  show kyma version, re-attach installation status, local setup
- Cluster with installation CR - status Installed - show kyma version, show installer status, local setup
- Cluster with installation CR - status Error - show kyma version, show installer status, do nothing

**Reasons**
Have the behavior more predictable, have a way to get installer status and trigger local setup

**Attachments**

**Comment by suleymanakbas91** [comment]
Implemented with #472.
