### ISSUE TITLE
Improved test logs

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/cli#404]
**Description**
1. The "kyma test logs" command should not require a mandatory test suite parameter. Instead, it should show the logs of the one existing test suite. If there are multiple suites available, select the newest available suite.

2. Furthermore, when having no failing tests but still some running tests, improve the error message to clearly indicate that you can call the same command with the --test-status flag to show the running logs

3. Add a new flag (--definitions) to filter the test definitions. So show the logs of pods which are related to the specified test definitions.

**Reasons**

Improve the user experience, several people gave feedback that the command behaves unexpected
**Attachments**

Also see https://github.com/kyma-project/cli/issues/32

**Comment by pbochynski** [comment]
I would not invest more in octopus.
