### ISSUE TITLE
Add command to get the health of a kyma cluster

### ISSUE THREAD

**Issue by sjanota** [kyma-project/cli#41]
**Description**
Have a "health" command to quickly get an overview of the cluster (in regards to problems).

It should focus on retrieving general health information and the installer status. Using --watch you can follow the health in case of unhealthyness (wait till it gets healthy)

Details:
- show console URL and check if it is reachable
- show simple health based on pod status in system namespaces (if there are pods which are not running or completed)
- have --watch option to wait till cluster is healthy on above criterias
- check status of installer

**Reasons**
Often you need a way to quickly check if all is running fine, like after installation you want to assure that all pods are running. With the health command it is easy to get that certainty and you can attach to it and wait till the condition is met.

**Comment by pbochynski** [comment]
Closed due to inactivity.
