### ISSUE TITLE
Provision: location flags consistency

### ISSUE THREAD

**Issue by clebs** [kyma-project/cli#410]
**Description**

Make the `location` flags consistent across all provision commands and improve the documentation.

Currently flags are:
- GKE: `location` accepts both a region or a zone.
- Azure: `location` accepts both a region or a zone.
- Gardener: has 2 flags;`region` accepts a region and `zones` accepts multiple zones.

We want all commands to have a single `location` flag that behaves the same way for all of them.

Additionally, the description is not clear and should be improved as follows (example taken from GKE `location flag`):
- Current description: "Location of the cluster."
- New description proposal: "Region (e.g. europe-west3) or zone (e.g. europe-west3-a) of the cluster."

**Comment by a-thaler** [comment]
Will not invest further in provisioning support, so we at least fixed the description to be more transparent
