### ISSUE TITLE
Support execution of test scenarios

### ISSUE THREAD

**Issue by k15r** [kyma-project/cli#412]
**Description**

As described in [Test-Execution-using-labels](https://github.com/kyma-project/community/blob/master/collaboration/sig-core/proposals/test-execution-using-labels.md) kyma-cli needs to be able to create cluster test suites using label queries.

labels describing scenarios follow this pattern:
<pattern>  ::= kyma-project.io/test.<scenario-name>=true

**AC**
- a subcommand lists all currently available scenarios
  all existing testdefinitions are queries for their labels. A _unique_ list of scenarios shall be printed
- the `test run` subcommand accepts one or multiple scenario names and creates a `clustertestsuite` with the corresponding labelmatcher
- the `test definitions` subcommand lists not only the name of the testdefinition but also the scenarios those test definitions are configured to be part of

**Comment by pbochynski** [comment]
I would not invest more in octopus.
