### ISSUE TITLE
kyma provision minikube -  is not relaying output errors

### ISSUE THREAD

**Issue by jcawley5** [kyma-project/cli#426]
If I run 
kyma provision minikube
it will sit at **Create Minikube instance: Start Minikube** forever.

After killing it and running
minikube start
I will get an error that sudo permissions need to be applied to particular items

After fixing the minikube config everything will work, but the kyma commands should be outputting the minikube errors.

**Comment by suleymanakbas91** [comment]
We introduced a timeout for all the minikube commands with [this change](09c114289b673efb28bebd2aadfa2de391b66c1c), so it won't run forever. We also added a note on the timeout message to `try running the command manually` so to solve any sudo permission problem. That looks like the only solution right now.

**Comment by a-thaler** [comment]
I tried it from home having a slack call in parallel. I started with empty minikube folder, so the ISO needs to be downloaded and I was running into the 3min timeout. I have no chance to change the timeout.
As the download already had 90% I think an increase to 5min will be good and making the option configurable already
