### ISSUE TITLE
Unable to provision minikube on hyper-v

### ISSUE THREAD

**Issue by guptar85** [kyma-project/cli#448]
Hello,

I have installed Docker Desktop for windows, Kubenetes-CLI and Minikube (v 1.62.2) - using Chocolatey, Now when I am trying to provision minikube using Kyma it is giving below error. 

However I can run minikube (without Kyma) and it is working perfectly fine using the same "External" Virtual Switch.

`C:\windows\system32> kyma provision minikube --vm-driver hyperv --hypervVirtualSwitch "External"
- Requirements verified
  Preparing Minikube using vm-driver 'hyperv'
- Minikube status verified
- Minikube config initialized
Create Minikube instance: Start Minikube
X Create Minikube instance
Error: Executing the 'minikube start --memory 8192 --cpus 4 --extra-config=apiserver.authorization-mode=RBAC --extra-config=apiserver.cors-allowed-origins='http://*' --extra-config=apiserver.enable-admission-plugins=DefaultStorageClass,LimitRanger,MutatingAdmissionWebhook,NamespaceExists,NamespaceLifecycle,ResourceQuota,ServiceAccount,ValidatingAdmissionWebhook --kubernetes-version=v1.16.3 --vm-driver hyperv --disk-size 30g -b kubeadm --hyperv-virtual-switch=External' command with output '* minikube 1.9.2 is available! Download it: https://github.com/kubernetes/minikube/releases/tag/v1.9.2
* To disable this notice, run: 'minikube config set WantUpdateNotification false'

! minikube v1.6.2 on Microsoft Windows 10 Enterprise 10.0.17134 Build 17134
* Selecting 'hyperv' driver from user configuration (alternates: [])
* Creating hyperv VM (CPUs=4, Memory=8192MB, Disk=30000MB) ...
E0502 16:01:57.074622   16960 main.go:106] libmachine: [stderr =====>] : Hyper-V\Start-VM : 'minikube' failed to change state.
The operation failed with error code '32788'.
At line:1 char:1
+ Hyper-V\Start-VM minikube
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Start-VM], VirtualizationException
    + FullyQualifiedErrorId : Unspecified,Microsoft.HyperV.PowerShell.Commands.StartVM

*
X Unable to start VM. Please investigate and run 'minikube delete' if possible: create: creating: exit status 1
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose
' and error message 'exit status 70' failed`

**Comment by hisarbalik** [comment]
This issue mainly caused by not enough free memory (8Gig for minikube) available or in some cases when hyper-v virtual switch has no access to the internet.

Tested on Windows 10 Pro, minikube 1.6.2 and kyma-cli 1.10/1.11, there is no issue found with kyma-cli.

Please ensure at least 8Gig free memory available for minikube instance and virtual switch has access to the internet

**Comment by a-thaler** [comment]
@guptar85 Can you please check the points mentioned by @hisarbalik.
As it most probably is not related to the CLI itself, will close the ticket for now.
If you think there is still something we should improve feel free to re-open.

**Comment by guptar85** [comment]
Yes it was an issue with RAM memory. Thanks for the info.
