### ISSUE TITLE
Support --kube-context flag

### ISSUE THREAD

**Issue by sjanota** [kyma-project/cli#46]
Kubeconfig file may consists of several contexts. While using kubectl you may provide `--context` flag if you don't want to use default one. Helm also supports it by providing `--kube-context` flag. We should do the same.

**Comment by a-thaler** [comment]
I would say that is a more advanced feature not really important for now. We should get back to it as soon as we have covered the main features.

The context flag allows to specify the context to use for a command. Assumption is set you have multiple contexts defined in your kubeconfig setup and you know how to manage them. If that is true, you usually have kubectl installed and you are managing the context with the "config" command. Then it is acceptable to just set the current context via kubectl and Kyma CLI will just use it as well.
