### ISSUE TITLE
Update installation documentation with Chocolatey instructions

### ISSUE THREAD

**Issue by dgalbraith** [kyma-project/cli#460]
**Description**
[Chocolatey](https://www.chocolatey.org) is a package manager for Windows which supports simple command-line driven installation for packaged applications.

A [Chocolatey package](https://www.chocolatey.org/packages/kyma-cli) has been built for the Kyma CLI which enables, after [Chocolatey installation](https://www.chocolatey.org/install), the Kyma CLI to be installed with:

```PowerShell
choco install kyma-cli
```

After a Chocolatey install the Kyma CLI is immediately available on the path without the need to update the **PATH** environment variable and can be updated to the latest version with:

```PowerShell
choco update kyma-cli
```
**Reasons**
The documentation should reflect available installation options.

**Comment by a-thaler** [comment]
Hi @dgalbraith,
thanks a lot for your contribution. We will test it with pleasure :)

As I never published to chocolatey yet, how the package can be updated by us to a newer version?

**Comment by dgalbraith** [comment]
Hi @a-thaler 

The Chocolatey package is setup to automatically update.  This is achieved using some tooling by @majkinetor ([the Chocolatey Automatic Package Updater Module](https://github.com/majkinetor/au) and a [CI pipeline](https://ci.appveyor.com/project/dgalbraith/chocolatey-packages) on [Appveyor](https://www.appveyor.com/).

The CI pipline currently executes once every 24 hours - if a new release version is found in the project's  [GitHub releases](https://github.com/kyma-project/cli/releases/latest) a fresh package is built using the released Windows binaries and pushed to the Chocolatey repository.

You  can also review the:
*  [source](https://github.com/dgalbraith/chocolatey-packages/tree/master/automatic/kyma-cli) for the packaging and updating;
* the last [run](https://ci.appveyor.com/project/dgalbraith/chocolatey-packages) from the CI pipline; and  
* a [Gist](https://gist.github.com/dgalbraith/aef61e2663a09f3dfdfa40482177e040) with the output of the latest daily CI build

Happy to get the project team included as package maintainers for Chocolatey or work with you to get the pacakge build incorporated into the CI pipeline for the project.

**Comment by clebs** [comment]
Extra documentation for the maintenance of the Chocolatey package (e.g. Description, screenshots, discussions, etc...) will be added together with the Homebrew maintenance documentation in https://github.com/kyma-project/cli/pull/457
