### ISSUE TITLE
Concatenation issue after migrating to Hydroform

### ISSUE THREAD

**Issue by pkosiec** [kyma-project/cli#473]
**Description**

After migration to Hydroform, CLI no longer concatenates passed configuration files correctly.

In CLI you use ---\n to concatenate all files:
```go
mergedInstallerFileContent := files[installerFile].StringContent + "---\n" + files[installerCRFile].StringContent
```

 but Hydroform splits them with `\n---\n`:

```go
func ParseYamlToK8sObjects(decoder runtime.Decoder, yamlContent string) ([]K8sObject, error) {
	resources := strings.Split(yamlContent, "\n---\n")
```

In case a file doesn’t have empty line at the end, it fails. (Another side question is if it is really necessary to concatenate config files and split them again)

**Comment by suleymanakbas91** [comment]
Solved by #474.
