### ISSUE TITLE
Installer override does not work with Installation CR

### ISSUE THREAD

**Issue by nachtmaar** [kyma-project/cli#475]
**Description**

Kyma CLI does not except Installation CR as override anymore:

```shell
$ kyma install -o ~/go-working/src/github.com/kyma-project/kyma/installation/resources/installer-cr-cluster.yaml.tpl
- Cluster info read
- Configurations validated
  Using the installation configuration from 'master'
  Installing Kyma in version 'master-d022112f'
- Installation source checked
- Installation files loaded
X Requesting Kyma Installer to install Kyma
Error: error: failed to parse configurations: unexpected object kind Installation, expected ConfigMap or Secret

```
**Expected result**

It works as it did before. It is already used in test-infra [here](https://github.com/kyma-project/test-infra/blob/669ab9de56c62de301b904b202947870e95ed0b3/prow/scripts/cluster-integration/kyma-integration-gardener-azure.sh#L202)
 

**Actual result**

Kyma CLI aborts installation with error

**Steps to reproduce**

**Troubleshooting**

```shell
$ kyma version
Kyma CLI version: stable-34-g211dd33
Kyma cluster version: N/A
```

**Comment by suleymanakbas91** [comment]
With kyma-project/cli#474, now you can pass a file with component list or an installation CR via the new `-c` flag.
