### ISSUE TITLE
gardener installation seems to not support verbose output

### ISSUE THREAD

**Issue by k15r** [kyma-project/cli#480]
**Description**

run a gardener installation like this:
`+ kyma provision gardener az --secret kyma-azure --name grdj0p21f --project kyma-prow --credentials /etc/credentials/gardener-kyma-prow/kubeconfig --region westeurope -z 1 -t Standard_D8_v3 --scaler-max 4 --scaler-min 3 --kube-version=1.16 --verbose`

I would expect to see some information about the current step, but there is no output on the console.

**Reasons**

we want to know whats going on. That way we could terminate installation early.
**Attachments**

**Comment by suleymanakbas91** [comment]
Thanks for reporting it @k15r! We are aware of and will work on this issue. I will close this one as we already have another github issue covering this https://github.com/kyma-incubator/hydroform/issues/103 :)
