### ISSUE TITLE
Terminal echo still off after error in "provision" task

### ISSUE THREAD

**Issue by smahr** [kyma-project/cli#488]
**Description**

When minikube is not correctly installed, for example if the hyperkit driver is not completely installed, kyma-cli fails, running into a timeout. 
After that, terminal echo is still set to off.

**Expected result**
Terminal echo shall be on after timeout errors. 

**Actual result**
Terminal echo is set to off. You can't just see what you type.

**Steps to reproduce**
- freshly install minikube
- do not finish the installation (would happen on first start)
- run "kyma provision minikube"
- wait until timeout

**Troubleshooting**

`$stty echoctl` does not work in that case, terminal is still working but not showing any feedback.

**Comment by clebs** [comment]
This issue is no longer reproducible, probably after updating the spinner library which correctly returns the terminal streams when canceling the context.
