### ISSUE TITLE
Have Kyma installer and Gardener App Hub yaml the same

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/cli#489]
**Description**

Kyma  should use the same configuration format for CLI and also for Gardener when comes to what components to choose and also overwrites. This will improve the user experience and also simplify our documentation if we want to provide Kyma templates in the future.

**Reasons**

Having a similar structure will allow users to use the same file if they install Kyma via cli or the use the App Hub inside Gardener. This will allow us to have specific templates for different levels of lightweight-heavyweight Kyma and be able to install via cli or Gardener.
![image](https://user-images.githubusercontent.com/478866/86753671-8d57c180-c040-11ea-9628-a049b38dad2d.png)

**Comment by valentinvieriu** [comment]
@a-thaler we still want to do this, right?
Stale Bot was here, so had to comment 😄

**Comment by a-thaler** [comment]
We will align the SAP-internal configuration to be aligned with the new way of installation as soon as it is ready.
