### ISSUE TITLE
Enhance the print summary with the installation duration  

### ISSUE THREAD

**Issue by sayanh** [kyma-project/cli#490]
**Description**

It'd cool to have the duration of installation in the [printsummary](https://github.com/kyma-project/cli/blob/master/cmd/kyma/install/cmd.go#L280).

**Reasons**

This will let us compare the platforms where the installation takes longer.

**Comment by a-thaler** [comment]
Looks like the duration is not based on the actual installation time on server side but is counted on client side. When getting disconnected that will not work out.
To prove it I just called install command on existing installation and it prints
```
Kyma installation took:		0 hours 0 minutes
```

**Comment by a-thaler** [comment]
There is no easy solution to achieve that, so for now we will stick to the local CLI time only
