### ISSUE TITLE
Minikube installation not working when DNS Port(Port 53) is being used by another service

### ISSUE THREAD

**Issue by rakesh-garimella** [kyma-project/cli#493]
**Description**
When we have dns port being used by another service eg. Cisco Umbrella the kyma installation is not working on minikube.
The installer is stuck at installing tiller.

**Expected result**

Kyma should be able to install in such scenarios too.

**Actual result**
Installation stuck in installing tiller.

**Steps to reproduce**

Try to install kyma on minikube using cli on a mac running cisco umbrella.

**Hints for solution**
One can start minikube with following flag as workaround: 

```
minikube start --hyperkit-vpnkit-sock=/.../vpnkit.eth.sock
```

Also look here: https://github.com/kubernetes/minikube/issues/3036#issuecomment-574943561

**Comment by a-thaler** [comment]
Seems that there is a problem when using the flag: https://github.com/kyma-project/kyma/issues/9439, please double-check before merging
