### ISSUE TITLE
Support of latest Minikube 1.12 and more relaxed support policy

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/cli#495]
**Description**
The minikube version used for testing is at 1.6 and the CLI is warning all the time when using the latest version. That can be quite annoying especially as a downgrade of minikube is complicated and it gets released frequently.

From the experience the 1.x.x line of minikube was very stable and compatible, so let's relax the policy by giving a warning in the CLI only of a different major version like 0.9.x gets used.

And update tests and documentation to latest version finally.

**Reasons**

Bad user experience when getting started with the CLI as the minikube version tends to be outdated always.
Supported version is outdated.

**Comment by suleymanakbas91** [comment]
We will wait until release 1.14 is out, and then continue with the upgrade.

**Comment by suleymanakbas91** [comment]
There is only one PR left to be merged. Adam takes it over now and will finish it by merging the PR and creating a new custom image.

**Comment by a-thaler** [comment]
The leftover will be covered with https://github.com/kyma-project/test-infra/issues/2671
