### ISSUE TITLE
Improved command output layout for install/upgrade command

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/cli#498]
**Description**

Over the time the output of the install command got polluted with non-relevant messages staying as persistent output, like the first line "Cluster info read".
Furthermore the feature of having detailed status of a step as dynamic log line (where the current line gets overwritten by the next line). Especially the installation status was a dynamic one-liner in the past outlining the current component status.

Goal:
- Re-think full output and re-design it to have mainly 3 lines like
  - Installation prepared, installing in version xxx taken from source yyy
  - Kyma installed successully
  - Local setup prepared
- Have enough detailed status underway as a one-liner
- Have troubleshooting info available per detailed step pointing out where to look at to get forward in case of a problem

**Reasons**
Better user experience, the output have the command should be concise and the info easy to grasp, still reflecting current status in a more detailed way.

**Attachments**

**Comment by lilitgh** [comment]
will be solved by https://github.com/kyma-project/kyma/issues/9029
