### ISSUE TITLE
Merge latest-published source into latest

### ISSUE THREAD

**Issue by suleymanakbas91** [kyma-project/cli#501]
**Description**

Currently, there are two different source options to install Kyma from the latest master, namely `latest-published` and `latest`. 

`latest` always uses the latest commit on the master branch. If there is not an installer image generated for it yet, then the installation fails.

`latest-published` finds the latest commit from the master with an available installer image and installs it. 

**Proposed Solution**

`latest-published` will be deleted so there will be only one option to install Kyma from the latest master. 

When the source is `latest`, CLI will check if there is an available installer image for the latest master:
- If there is, it will continue installing. 
- If not, it will ask the user if it should check for the latest published installer image to be used for installation. If the user declines, the installation will not continue and an appropriate error message will be shown.

**Comment by a-thaler** [comment]
I would like to use the chance and rename it to something like "master" to indicate using latest master revision. "Latest" tells me that it is latest release.
