### ISSUE TITLE
Kyma cli does not show the console url

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/cli#518]
**Description**

I'm using  1.14.0-rc1 version and after the installation it mentions that the console is not installed. 
The pods are available and reachable, just the link is not displayed in the cli.
Running the installation again, triggers the Kyma Console link to be displayed in CLI

![image](https://user-images.githubusercontent.com/478866/88272740-79b38880-ccd9-11ea-8bdb-b2356ef45584.png)

**Expected result**

The Kyma console link should be provided 

**Actual result**

![image](https://user-images.githubusercontent.com/478866/88272468-0e69b680-ccd9-11ea-8f60-3d6d33994be6.png)

**Comment by a-thaler** [comment]
I remember that @smahr was entering a wrong sudo password for adding certificates to keychain.
@valentinvieriu Have you entered them correct?

**Comment by valentinvieriu** [comment]
I think was an user mistake. I've used the 1.13 for the first call and then 1.14.0-rc1 for second

**Comment by a-thaler** [comment]
The virtualservice name of the console has changed for kyma 1.14.0. That change is included in CLI 1.14 but not in 1.13.
Will mark it as invalid.
