### ISSUE TITLE
Make kyma install command idempotent

### ISSUE THREAD

**Issue by nachtmaar** [kyma-project/cli#542]
**Description**

When using kyma cli to install Kyma, you only have one shot to install Kyma. If an error occurs during installation, one needs to trigger the installation again. However, there is a high chance that `kyma install` will reject to start another round of installation.
Examples when this can be useful:
- One tried installing e.g. kyma 1.13 but was using kyma cli 1.14 (breaking change, kyma cli 1.13 is required to create the helm secret).

```shell
$ kyma-knative-kafka-install /tmp/azure-secret.yaml 1.13.0
- Cluster info read
X Checking existence of previous installation
Error: Failed to get the installation status

$ declare -f kyma-knative-kafka-install
kyma-knative-kafka-install () {
        if [[ $# -lt 1 ]]
        then
                echo "Usage: kyma-knative-kafka-install <installation-override-secret> [<installer-image]"
                echo "You can use `kyma-azure-namespace` to create the installation overrides"
                return
        fi
        kyma install --source ${2:-latest-published} -o "$1" -o ${KYMA_SOURCE}/installation/resources/installer-config-production.yaml.tpl -c ${KYMA_SOURCE}/installation/resources/installer-cr-azure-eventhubs.yaml.tpl -o ${KYMA_SOURCE}/installation/resources/installer-config-azure-eventhubs.yaml.tpl --timeout 120m
}

```

- Installation overrides are passed with `kyma install -o`, however during the installation you realize that kyma-operator fails installating a particular component because of the installation overrides. Making the `kyma install` command  idempotent would allow to adjust the overrides and try again.

Currently, the only way to start a new installation is as follows:
```
kubectl delete crd releases.release.kyma-project.io
kubectl delete crd installations.installer.kyma-project.io
kubectl delete serviceaccounts -n kube-system tiller
kubectl delete ns kyma-installer
kubectl delete clusterrole all-psp
kubectl delete clusterrolebindings.rbac.authorization.k8s.io all-psp
kubectl delete clusterrole kyma-installer-reader
kubectl delete clusterrolebindings.rbac.authorization.k8s.io kyma-installer
```

**Reasons**

`kyma install` command should be easy to use. If a user makes a mistake in the install command (e.g. installation overrides), the user should be able to trigger a new installation without knowing kyma internals.

**Attachments**

**Comment by pbochynski** [comment]
Related issue https://github.com/kyma-project/kyma/issues/10178

**Comment by pbochynski** [comment]
Replaced by idempotent deploy command (alpha for now).
