### ISSUE TITLE
Command for connecting a System

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/cli#554]
**Description**

A typical scenario which Kyma users are doing for administrative purpose is to setup a system, bind it to a namespace and get a token. Having that the administrator will start the pairing process on the connecting system.
To have that scenario doable without UI in a convenient way a new command will be great.

The new command should be "alpha" for now to gather experience with it first and have the freedom to change things still.

The name could be something like "kyma system connect <appName> -n myNamespace"

Internally, the command should place an Application, ApplicationMapping and TokenRequest resource. If an Application or ApplicationMapping resource already exist it should not fail but update. A TokenRequest must be created always fresh.

It should have a nice output with application id, application name and token but also a -o yaml option to have an output in a parsable format.
**Reasons**

Simplifying life of administrator not needing to know the kyma CRDs

**Attachments**

**Comment by clebs** [comment]
After discussing the design of this command and future commands with @a-thaler, we decided to take the `kubectl` approach and have first level commands that manipulate cluster resources be verbs (create, get, delete, etc...).

According to this design:
- The command to add a `system` will be: `kyma create system -n ${NAMESPACE} ${NAME}`.
- The command will output the created resource, a token to access it and any additional information such as wwarnings in a structured manner (either nice print for the user or proper yaml).
- Running the command will fail if the resource already exists.
- Running the command with the `--update` flag will apply any changes to the resource and create a new token.

**Comment by clebs** [comment]
Created the new `kyma create system` command as described in the PR: #575
