### ISSUE TITLE
Fetch schema for config.yaml for IDE validation/autocompletion 

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/cli#576]
**Description**

Provide a way to fetch available configuration options for config.yaml and store them in  a schema dedicated for the IDE.

Schema should contains possible enum values for:
- function runtime (nodejs, pyhton, etc) 
- triggers (available events in the given namespace) 
 
User can validate config.yaml against the schema.
User might consume the schema in IDE plugin and benefit from autocompletion.

**Reasons**

By introducing autocomplete for config.yaml in the IDE, we are making the configuration process easier for the user.

**AC**
 - the schema is downloaded upon first `kyma function init` command
 - as the available options may change ( i.e new triggers becoma available ) user can sync the schema with the current state of the runtime
 - update documentation - recommendation about possible ways of config validation against the schema
 - support at least 2 popular IDEs (e.g. VS code, GoLand)

**Comment by Disper** [comment]
@m00g3n might have a working example for the VScode

**Comment by pPrecel** [comment]
There is one bug in the `yaml` extension for the VScode that may be annoying in the context of these changes. Everything is described here: https://github.com/redhat-developer/vscode-yaml/issues/715
