### ISSUE TITLE
Upgrade kubernetes and kyma libraries to latest versions

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/cli#578]
**Description**
In order to use the newest typed APIs of kubernetes and Kyma these dependencies needs to be updated.
Most probably that will require an upgrade of terraform within hydroform: https://github.tools.sap/kyma/management-plane-config/pull/648 and the go client library.

**Reasons**
Usage of latest typed APIs is not possible at the moment forcing people to use untyped API.

**Attachments**

**Comment by clebs** [comment]
# CLI & Hydroform upgrade plan

## Motivation
The main trigger for this upgrade is the fact that the CLI and Hydroform should always use the latest released Kyma APIs.
Importance is increasing becasue we are starting to add CLI commands and Hydroform packages that manage Kyma CRs.

## Upgrade points
Upgrade points are listed by need and how they affect each other:
1. [CLI] Upgrade Kyma API to latest release -> Custom Istio API (github.com/kyma-project/kyma/components/api-controller/pkg/clients/networking.istio.io) was removed, we need to migrate to the official istio clientset.
2. [CLI] Migrate to official Istio API (github.com/istio/client-go) -> It requires the 1.18 K8s API and client-go
3. [CLI] Upgrade k8s and client-go to 1.18 respective versions -> k8s, client-go, Terraform dependencies will break on Hydroform
4. [Hydroform] Upgrade Kyma and k8s APIs
5. [Hydroform] Upgrade Terraform -> Might require a big refactor on the terraform operator

## Complexity reduction areas
- CLI/Hydroform coupling: Reduce the complexity between Hydroform and the CLI -> For example, both import `client-go` and there might be a way to only have the import in the CLI, making the relationship between both much easier to maintain.
- Cleanup: Remove as many dependencyes as possible if they are not really needed or can be removed with a small refactor.

**Comment by clebs** [comment]
Upgraded Hydroform to use the kubernetes API 0.18: https://github.com/kyma-incubator/hydroform/pull/125

**Comment by clebs** [comment]
Upgraded Octopus to use kubernetes API 0.18 and migrated to go modules fully: https://github.com/kyma-incubator/octopus/pull/43

**Comment by clebs** [comment]
Upgraded the Kyma CLI: #596
- Migrated k8s APIs & go client to v0.18
- Replaced custom kyma Istio API with the official one
- Updated docker library
- Analyzed module graph and removed unneeded replace directives
- Updated hydroform (provision and install)
- Updated Octopus
