### ISSUE TITLE
Change junit output to include testsuitename in testname

### ISSUE THREAD

**Issue by k15r** [kyma-project/cli#579]
**Description**

currently all tests are prefixed with '[testing] ' in the junit output of 'kyma test status'.
It would be useful to replace this prefix with the name of the testsuite that the test was part of.

**Reasons**

if the junit results are displayed in prow using spyglass there is no way of figuring out as part of which testsuite a single test was executed. If all test names would be prefixed with the testsuite name it would be easier to figure out when a test was executed.
<img width="671" alt="Screen Shot 2020-09-09 at 19 27 05" src="https://user-images.githubusercontent.com/292906/92633441-14d8df80-f2d3-11ea-8b76-77bf796e73e2.png">

**Attachments**

[junit_Kyma_octopus-test-suite-1599669786.xml.txt](https://github.com/kyma-project/cli/files/5196987/junit_Kyma_octopus-test-suite-1599669786.xml.txt)
[junit_Kyma_octopus-test-suite-1599668903.xml.txt](https://github.com/kyma-project/cli/files/5196988/junit_Kyma_octopus-test-suite-1599668903.xml.txt)

**Comment by clebs** [comment]
Review done, waiting for approval from test infra for the merge:
https://github.com/kyma-project/cli/pull/580#issuecomment-690103954
