### ISSUE TITLE
Improve test logs to show which test failed or succeded.

### ISSUE THREAD

**Issue by dbadura** [kyma-project/cli#582]
**Description**

When Prow execute more than one test, the logs are as follow:
```
Waiting for test suite to finish: 0 out of 3 test(s) have finished (Succeeded: 0, Failed: 0, Skipped: 0)...
Waiting for test suite to finish: 0 out of 3 test(s) have finished (Succeeded: 0, Failed: 0, Skipped: 0)...
Waiting for test suite to finish: 0 out of 3 test(s) have finished (Succeeded: 0, Failed: 0, Skipped: 0)...
Waiting for test suite to finish: 1 out of 3 test(s) have finished (Succeeded: 1, Failed: 0, Skipped: 0)...
Waiting for test suite to finish: 2 out of 3 test(s) have finished (Succeeded: 2, Failed: 0, Skipped: 0)...
```
As a user I don't know which test suite succeeded or failed. 
It would be good that the cli will print which test succeeded or failed.
**Reasons**

This feature will shorten feedback waiting time to user who wait for specific test to finish.
**Attachments**

**Comment by a-thaler** [comment]
To gather your input, how would you imagine the output so that you are satisfied? Instead of the counter you want to print the list of test cases?

**Comment by a-thaler** [comment]
Relates a bit to https://github.com/kyma-project/cli/issues/404

**Comment by dbadura** [comment]
I thought about information that this tests failed or succeed. Like this:
```
Waiting for test suite to finish: 0 out of 3 test(s) have finished (Succeeded: 0, Failed: 0, Skipped: 0)...
Test suite xyz failed/succedded.
```

The list of succeeded or failed test also sounds good.

What do you think about printing logs from tests in case of failure?

**Comment by pbochynski** [comment]
I do not think we should invest here. Let's go to fast-integration train :)
