### ISSUE TITLE
Transparent CLI compatibility

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/cli#584]
**Description**
At the moment it is not that obvious how the CLI compatibility is defined in regards to: Can you use Kyma-CLI 1.15 to install Kyma 1.14. Can you use Kyma-CLI 1.15 to use a command like "kyma console" on a kyma 1.14 cluster. Can you use Kyma-CLI 1.15 to install Kyma 1.16

We need to provide an explicit documentation on what is supported and also assure that we have tests for that.

Ideally, a Kyma-CLI version supports the last 2 Kyma versions, so Kyma-CLI 1.15 supports Kyma 1.15,1.14,1.13. It will not support Kyma 1.16

Requirements:
- Have a clear docu on what is supported
- Have an integration job assuring compatibility for all commands with default settings

**Reasons**
It must be transparent to the user what to expect

**Attachments**

**Comment by clebs** [comment]
Added compatibility docs: #604 
Added compatibility jobs: https://github.com/kyma-project/test-infra/pull/2813
