### ISSUE TITLE
Missing logs in prow jobs

### ISSUE THREAD

**Issue by jasiu001** [kyma-project/cli#586]
**Description**

When the upgrade tests on `pre-master-kyma-gke-upgrade` prow job failed then it is possible to see logs from those tests.
Unfortunately, the logs in the raw build-log.txt are cut off. This can be seen under this [link](https://prow.k8s.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-upgrade/1301056363010461697).
Logs are different between what is in the raw text file and in JUnit section (click `1/21 Tests Failed.`).
The code responsible for display logs is [here](https://github.com/kyma-project/test-infra/blob/master/prow/scripts/kyma-testing.sh#L121)

**Expected result**

The same logs should be in the raw file and in the JUnit section.

**Actual result**

Logs are cut off in raw file.

**Steps to reproduce**

Whenever the `test-e2e-upgrade-execute-tests` fail the logs are cut. I have not checked other tests.

**Comment by a-thaler** [comment]
Thanks for reporting the issue, indeed it was a bug in the "kyma test logs" command which we fixed.
