### ISSUE TITLE
Default namespace support in CLI

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/cli#588]
**Description**
Recently a new command "create system" was introduced being namespace aware. Unfortunately it requires an explicit namespace which often is not needed as the namespace should be taken from current kubceonfig context.

Goal is to introduce support in the CLI codebase for retrieving the default namespace from the current kubeconfig context. That feature should be then used in the mentioned command.

**Reasons**
Expected behaviour for typical CLI target group as it is known from kubectl usage

**Attachments**

https://github.com/kyma-project/cli/issues/554

**Comment by clebs** [comment]
Added the desired behaviour as part of the Kyma CLI interface for all commands to be able to use it.
Details on the PR:
https://github.com/kyma-project/cli/pull/590
