### ISSUE TITLE
Upgrade command does not trigger another upgrade when there is an active upgrade already running

### ISSUE THREAD

**Issue by nachtmaar** [kyma-project/cli#592]
**Description**

As a [cloud native software engineer](https://github.com/kyma-project/community/blob/master/manifesto/personas.md#matthew---cloud-native-software-engineer), I want to be able to quickly try out new Kyma versions and sometimes even customize it. For customization I need to trigger an upgrade in order to install the changes. For that purpose I want to use Kyma CLI because it is the easiest way to do it.
When I do a mistake, I want to have the possibility to correct my bug and try another upgrade (even though my previous upgrade is still pending, but will never succeed because of the bug I introduced).

Example:

- fresh kyma installed successfully
- upgrade was triggered with my custom image
- upgrade is pending, but chart is in failing state and it won't recover
- I have fixed my bug and want to upgrade with a new installer image

However that is currently not possible:

```shell
$ kyma upgrade -s nachtmaar/kyma-installer:b40ca766f -c installer-cr-cluster.yaml.tpl
- Cluster info read
- Installation in version '590c0beab' is already in progress
- Re-attaching installation status
/ install component eventing
```

**Expected Behaviour**
Kyma CLI let's me upgrade using my custom image no matter in which state the cluster currently is

**Actual Behaviour**
Kyma CLI is watching the pending upgrade and not deploying the new installer image.

**Possible Solution**
A solution could be to introduce a "--force" flag for this use case.

**Comment by lilitgh** [comment]
Will be solved by https://github.com/kyma-project/kyma/issues/10297
