### ISSUE TITLE
Lack of newline while appending to /etc/hosts

### ISSUE THREAD

**Issue by dbadura** [kyma-project/cli#593]
**Description**
When the installation via kyma cli is finishing, the cli add entry to `/etc/hosts` without new line.

The entry in `/etc/hosts` should have new line according to POSIX and the `/etc/hosts` can be badly interpreted by scripts or other programs.

**Expected result**
The CLI add entry with newline at the end.

**Actual result**
The entry in `/etc/hosts` is not terminated by new line.

**Steps to reproduce**
Install kyma or trigger adding to host process.

**Troubleshooting**

**Comment by clebs** [comment]
Added newline to `/etc/hosts` entry if not present.
