### ISSUE TITLE
Tutorial describing usage of new CLI commands for serverless support

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/cli#595]
**Description**

Describe necessary steps for function developer to create a sample function via CLI commands
Basic scenario to describe in [Tutorial section](https://kyma-project.io/docs/cli/#tutorials-tutorials): 
 - `init` a function locally 
 - code the function (introduce some local computation with dependency to external library but w/o any 3rd paty service)
 - run the function locally 
 - `apply` a function 
 - inspect the runtime ( via kubeclt ) - to see the function
 - add a configuration for function trigger
 - finally, `apply` the function and inspect the resources on the runtime via kubectl 
 
Mention additional options for `apply` command:
 - `apply` a function with `--dry-run` option - for demonstration
 - `apply` the function with `-- template` option - for demonstration AND explaining it might be useful for syncing workloads the GITOPS fashion

**Area**

* CLI
* Serverless

**Reasons**

Allow easy start for function developers.
Familiarise them with:
 - basic workflow 
 - config.yaml syntax.
 
**Assignees**

@technical-writers

**Attachments**

**Comment by kwiatekus** [comment]
Please remove the k3s context. It should not be mentioned as a prerequisite. 
It's enough to have access to any kyma runtime based on any compliant k8s engine. 
Readers may have the impression that they need to install k3s to learn the power of the serverless CLI commands

**Comment by kazydek** [comment]
Closing as the tutorial was done and fixed.
