### ISSUE TITLE
upgrade from local sources without changing docker image tag

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/cli#597]
**Description**

When having a non-local kyma cluster and you update it from local using the upgrade command, you end up changing the custom-image name for every upgrade.

When developing a Kyma feature I'm using the upgrade from local frequently. Whenever I want to test a new change I call the upgrade command like that:
`upgrade -s local --custom-image=xxx/installer:test`
Unfortunately, the pull policy of the installer image is set to "IfNotPresent", with that the new image gets not used at least at the second call. So I need to rotate the image tag on every call and need to clean up my docker registry.

Please find a way so that this command can be used repeatedly with the same image.

**Reasons**

**Attachments**

**Comment by clebs** [comment]
It is probably not possible to delete the image from the local registry on the cluster.
Also the Always pull policy might not be good.

A way for this to work might be adding the last digits of the current timestamp to the image tag.

**Comment by pbochynski** [comment]
The installer is discontinued. We will not work on it.
