### ISSUE TITLE
Refactor the system commands to use the typed API from Kyma

### ISSUE THREAD

**Issue by clebs** [kyma-project/cli#602]
**Description**

After finishing the CLI k8s Upgrade in #578, it is now possible to import the APIs and CLientSets for the different components.
Refactor the usage of the unstructured dynamic API calls to create systems into the typed API.

**Reasons**

Safety and better compatibility when communicating with the application connector.

**Comment by a-thaler** [comment]
Not valid anymore with new way of installation
