### ISSUE TITLE
terminal output in junit report may result in invalid xml file

### ISSUE THREAD

**Issue by k15r** [kyma-project/cli#611]
**Description**

**Expected result**

junit file can be rendered correctly

**Actual result**

Some terminal output seems to break the XML file.
chromes XML engine complains about invalid xml

```
This page contains the following errors:
error on line 9 at column 47: Input is not proper UTF-8, indicate encoding !
Bytes: 0x1B 0x5B 0x3F 0x32
Below is a rendering of the page up to the first error.
```

This also leads to incomplete output on prow as prow also cannot render the xml.

**Attachments**

[junit_Kyma_octopus-test-suite-1602592255.xml.zip](https://github.com/kyma-project/cli/files/5372147/junit_Kyma_octopus-test-suite-1602592255.xml.zip)

**Comment by pbochynski** [comment]
@k15r I see it is merged. Can you close the issue? BTW please remember about labels.
