### ISSUE TITLE
Logic of OwnerReferences for functions

### ISSUE THREAD

**Issue by pPrecel** [kyma-project/cli#614]
**Description**

All new `Triggers` declared in the `config.yaml` have OwnerReference set to the parent Function (after applying). We should discuss and implement the mechanism of controlling this functionality (for example by adding a new flag `--SetOwnerReference`). 

Now deleted functions delete all `Triggers` because `OwnerReference` covers this case. We should implement the functionality of removing triggers not based on `OwnerReferences`.

**Attachments**

[Suggestion from the review](https://github.com/kyma-project/cli/pull/606#discussion_r500994973)

**Comment by kwiatekus** [comment]
Closing due to lack of priority.
The default mode that assurefs the owner reference relation between trigger and its parent function seems enough ( judging that no user was requesting an option to detach them )
