### ISSUE TITLE
Provision: AKS on windows fails

### ISSUE THREAD

**Issue by clebs** [kyma-project/cli#619]
**Description**

Provisioning an AKS cluster on windows fails with the following error:
```
Could not download module "root"
(-from-module="git::https://github.com/kyma-incubator/terraform-modules//azurerm_kubernetes_cluster?ref=v0.0.3":1)
source code from
"git::https://github.com/kyma-incubator/terraform-modules?ref=v0.0.3": error
downloading 'https://github.com/kyma-incubator/terraform-modules?ref=v0.0.3':
C:\Program Files\Git\cmd\git.exe exited with 128: fatal: could not create work
tree dir
'\\?\C:\Users\dibs\.kyma\clusters\azure\akskyma\kyma-cluster\.terraform\init-from-module\root':
Invalid argument
```
**Expected result**

The module is downloaded properly into the working directory and the cluster is provisioned.

**Actual result**

The path to the working directory is invalid for git to download the module.

**Steps to reproduce**

- Run `kyma provision aks` on a windows machine.

**Troubleshooting**
There was a similar issue in the past with wrong file paths on windows and we fixed it adding the `\\?\` prefix (see the path on the error message). But this fix could be causing the problem for git to download the module.

The solution most likely is to pass the path without the prefix when using a module download on windows.

**Comment by tobiscr** [comment]
Will investigate a bit further and come up with an estimation.
