### ISSUE TITLE
Support lite and full installation types

### ISSUE THREAD

**Issue by igor-karpukhin** [kyma-project/cli#66]
How about to add two types of installation:
* All kyma components + Prometheus/kiali/grafana (full)
* All kyma components without Prometheus/kiali/grafana (lite)

The idea is, that by default `kyma-cli` will install the lite version but one may provide a flag (`--full`) to install monitoring subsystem as well.

**Comment by a-thaler** [comment]
I agree that we need to make it much more convenient to install Kyma in different setups. Supporting just two profiles I think is not going far enough.
I will create a dedicated epic to cover the whole installation topic and we can simplify custom modules, predefined profiles, custom settings.
