### ISSUE TITLE
k3s support

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/cli#670]
**Description**
Add support for k3s/k3d in a similar we have wit minikube with the goal of replacing minikube support for local development. 

AC:
- Support for darwin/windows/linux
- Assumption is that k3d is installed, if not fail and print nice info on how to install
- Assure that proper major version is available
- Test if it works with DNS thingy and VPN
- Have resource consumption configurable
- Have cluster name configurable

**Reasons**
The known problems with minikube (restart, nodePort) are not present, the resource consumption is much better and it is faster. 

**Attachments**
Epic: https://github.tools.sap/kyma/backlog/issues/1045 (was before: https://github.tools.sap/kyma/backlog/issues/1005 )
Closed PR trying to add k3s support: https://github.com/kyma-project/cli/pull/508
Working scripts for e2e k3s setup: https://github.com/kyma-incubator/local-kyma

**Comment by tobiscr** [comment]
Assigned this ticket to @clebs (topic owner) and me as contributor.

**Comment by tobiscr** [comment]
See PR 678

**Comment by tobiscr** [comment]
@a-thaler : added #680 as the docs should be extended after replacing `minikube` with `k3s`. The doc pages are currently not covering the alpha command related parts.

**Comment by tobiscr** [comment]
Some details how ACs are implemented:

* Support for darwin/windows/linux
K3d works on MAC and Linux (see installation guides on [https://github.com/rancher/k3d#get](https://github.com/rancher/k3d#get)). For Windows is currently no native support provided, but using a VM will work out tool. This will be covered in docs (see #680).

* Assumption is that k3d is installed, if not fail and print nice info on how to install
Installation command will fail with message to install K3d (see https://github.com/kyma-project/cli/blob/master/internal/k3s/k3s.go#L83). Error message if K3d is missing will be improved in PR #683.

* Assure that proper major version is available
Major version is tested in https://github.com/kyma-project/cli/blob/master/internal/k3s/k3s.go#L67.


* Test if it works with DNS thingy and VPN
No DNS issue detected yet, but getting the installation working on K3d is still ongoing and will be fixed (if issue exists) there.

* Have resource consumption configurable
As K3d is running in local Docker daemon, the Docker specific resource limitations have to be used. K3d doesn't support resource limitations options. This will be covered in the docs (see #680).

* Have cluster name configurable
Cluster name can be configured as CLI option (see https://github.com/kyma-project/cli/blob/master/cmd/kyma/alpha/provision/k3s/cmd.go#L42).

**Comment by clebs** [comment]
Follow up issue for installation on K3s:
https://github.com/kyma-project/cli/issues/685
