### ISSUE TITLE
CLI integration test for new experimental install commands

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/cli#671]
**Description**

Have a new CLI e2e pipeline (similar to the minikube integration test) which will verify all new experimental commands e2e
Steps could be:
•	kyma alpha provision k3s (https://github.com/kyma-project/cli/pull/508)
•	kyma alpha install –profile=evaluation --verbose
•	kyma test run kiali
•	kyma uninstall
•	kyma install

**Reasons**

**Attachments**

**Comment by tobiscr** [comment]
@clebs : are you already working on it? If not, I would follow-up this part and setup a test pipeline for K3S.

**Comment by tobiscr** [comment]
As K3S CLI support is still ongoing, we merged the refactored testing pipeline to Prow now. We will update it as soon as the K3s story has reached a proper maturity to switch from Minikube to K3s.

**Comment by clebs** [comment]
Cli integration job on K3s is green and is required on all PRs.
For example see: https://github.com/kyma-project/cli/pull/883
