### ISSUE TITLE
Suppress kyma password log in specific cases

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/cli#68]
At the moment the "kyma install" command prints the following after successful installation:
```

Kyma is installed in version 1.0.0
Kyma console:     https://console.kyma.local
Kyma admin email: admin@kyma.cx
Kyma admin pwd:   xxx

Happy Kyma-ing! :)
```

Please suppress the password log if:
- provided by the --password option
- in non-interactive mode

**Comment by a-thaler** [comment]
Done

**Comment by igor-karpukhin** [comment]
Addressed in https://github.com/kyma-project/cli/pull/79
