### ISSUE TITLE
New Installation: Cover k3s specific configuration and edge-cases in docs

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/cli#680]
**Description**

Extend CLI documentation for K3s provisioning with these topics:

* Configuration of Docker resource limits for K3d (TBD: figure out limits used in different profiles).
* Known edge-cases when using K3s locally
    * allocated ports on host when using K3s
    * min-version of k3d
    * no traefik-ingress for K3s should be
    * pre.conditions to deploy Kyma on a self-created cluster
    * etc.

These points become relevant **after** replacing the local `minikube` setup with `k3s` (related to #670).

**Area**

CLI

**Reasons**

Switching to `k3s` introduces new edge cases and configuration options. 

**Assignees**

Dev team / TW

**Attachments**

**Comment by a-thaler** [comment]
Current documentation will be good enough for now
