### ISSUE TITLE
New installation: cutover and deprecate old install command

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/cli#693]
**Description**

After the installation and testing phase is finished, the `alpha` command had to be removed and the new deploy and undeploy commands have to become the recommended way to install Kyma. The old install command and Minikube support have to be marked as deprecated.

**Reasons**

Cutover of new installation.

**Attachments**

-

**Comment by a-thaler** [comment]
Duplicate of https://github.com/kyma-project/kyma/issues/10812
