### ISSUE TITLE
Migrate installation scripts

### ISSUE THREAD

**Issue by sjanota** [kyma-project/cli#7]
This ticket tracks what needs to be done in order to fully migrate Kyma installation scripts to this CLI. 

### Local installation (`run.sh`)

- [x] Start minikube during default installation *There is a separate command to install minikube*
- [x] Allow to skip minikube start (`--skip-minikube-start`) *See above*
- [x] Use default VM driver for OS *Different defaults are provided in a transparent way depending on if it is linux, darwin or windows*
- [x] Allow to set VM driver for minikube (`--vm-driver`) *Realized with `--vm-driver` option*
- [x] Allow to set custom admin password (`--password`)
- [x] Allow to specify custom Installation CR (`--cr`) *Might be realized by allowing to specify multiple --config yaml files which are getting merged together with the base yaml file.*
- [ ] ~~Start in Knative mode (`--knative`)~~ _Knative will be default soon_
- [x] Install Kyma from local sources *Realized with `--local` option*

### Azure installation

- [ ] Generate Installation CR from template (`create-cr.sh`)
- [ ] Generate config overrides (what `replace-placeholder.sh` is used for)
- [ ] Create subcomponents configmap (`configure-comppnents.sh`)

### Others
- [x] Run tests (`testing.sh`) *There is a separate command to test kyma*
- [ ] Watch pods (`watch-pods.sh`)
- [ ] General approach to `installation/resources`

**Comment by sjanota** [comment]
I think we already migrated what seemed to be necessary. All that has left probably will be done differently in CLI. I think we can close this issue.
@a-thaler What do you think?

**Comment by a-thaler** [comment]
That ticket was good for tackling the local installation. All other topics we should tackle by dedicated epics.
