### ISSUE TITLE
New installation: support values- and component-files from remote locations

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/cli#701]
**Description**

It has to be possible to provide value files and also the component-file from remote locations to the `alpha deploy` command and not just from the local filesystem.

**Reasons**

This gives our users the flexibility to manage these files in a central place.

**Attachments**

**Comment by a-thaler** [comment]
In general works as expected, still the in-line documentation does not indicate that URLs are supported. Furthermore a yaml validation error does not indicate which file caused the problem (I used components and values file overwrite at the same time). At least indicating that the values files or the components file caused a problem is required to simplify users life.

**Comment by tobiscr** [comment]
Missing API doc update will be fixed in https://github.com/kyma-project/cli/pull/820/files

**Comment by tobiscr** [comment]
Fix for non-expressive error message when providing invalid YAML / JSON files will be fixed as part of https://github.com/kyma-incubator/hydroform/pull/230
