### ISSUE TITLE
New installation: show a summary at the end of the Kyma deployment process

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/cli#702]
**Description**

A Kyma deployment command (`alpha deploy`) should show a summary of the deployment process (e.g. consumed time, tracked errors/retires per component etc.) at the end of the process.

The current success message at the end of the deployment should be migrated into the summary. Verify whether it's useful to add a template-engine.

AC:

* Show consumed time for the process
* Show consumes time per component
* In case of errors, show the error message
* Show installation hint for certificates on
    * Linux
    * Mac
    * Windows

**Reasons**

A summary will provide a valuable feedback for users and developers to identify optimisation options or failure-prone component installations.

**Attachments**

**Comment by clebs** [comment]
Added summary as the one in the old install command for the new alpha deploy command:
<img width="520" alt="Screenshot 2021-02-23 at 17 42 00" src="https://user-images.githubusercontent.com/1059661/108882964-2dc91900-7605-11eb-9ca4-159d9ab32c9c.png">
