### ISSUE TITLE
Make request for root rights more explicit

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/cli#71]
**Description**
The "provision minikube" command adds entries to the hosts file by executing a sudo command. The logs in the CLI only says that you should enter your password, it is not explaining why. If I don't want to grant root access, I have no chance to skip it.

**Goal**
- Improve the log message and explain why it ask for root rights
- If adding to hosts file fails, just continue and print manual instructions as done for windows

**Comment by a-thaler** [comment]
Now there is more info text and it continues on failures with the manual action explained

**Comment by igor-karpukhin** [comment]
Addressed in https://github.com/kyma-project/cli/pull/75
