### ISSUE TITLE
provisioning k3s cluster fails with k3d 4.0 Error: unknown flag: --switch-context

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/cli#718]
**Description**

The Provisioning of the k3s fails when using the latest k3d 4.0.

**Expected result**

The provisioning should happen

**Actual result**
We've got an error instead
```
time="2021-01-25T10:33:29+01:00" level=fatal msg="unknown flag: --switch-context"
': exit status 1
```

**Steps to reproduce**

- Install latest version of k3d (4.0 )
- use the master cli and build project
- run `./bin/kyma-darwin alpha provision k3s`

**Comment by tobiscr** [comment]
Upgrade to K3d 4.0.0 happens as part of PR #735
