### ISSUE TITLE
using the -w flag with kyma alpha deploy does not work as expected

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/cli#721]
**Expected result**

providing a -w flag should take the source from the provided folder
**Actual result**

```

Error: Components list 'workspace/installation/resources/components.yaml' not found

```

The app still expects a workplace folder

**Steps to reproduce**

- use master
- compile latest
- use 

```sh
kyma-darwin alpha deploy \
-p evaluation \
--source=local \
--domain=local.kyma.dev \
--workspace=/Users/xxx/go/src/github.com/kyma-project/kyma/ \
--verbose
```

**Troubleshooting**

**Comment by a-thaler** [comment]
fixed by linked PR
