### ISSUE TITLE
New Installation: create architectural documentation new Kyma provisioning and installation mechanism

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/cli#734]
**Description**

An architectural documentation of the new installation approach is required. It has to cover:

* High-Level Arch diagram of current and previous installation mechanism
* Metadata handling (content of cluster-metadata and Kyma-metadata), their purpose (e.g. used in uninstall and for upgrade-check) and potential edge-cases (e.g. risk if users are manually modifying it etc.)
* Component-list (which data can be defined in components list, benefits in longterm by getting more flexible)
* Install/deploy command (describe parts which happen synchronously and parallel, downloading Kyma sources etc.)
* Uninstall command (describe parts which happen synchronously and parallel, namespace deletion etc.)
* Provision mechanism (benefits of K3s, benefits/disadvantages of using K3s bundled in CLI instead of using external `k3d` tool)
* ...

**Area**

CLI documentation

**Reasons**

Documentation doesn't cover architectural perspective of CLI.

**Assignees**

@kyma-project/technical-writers
@tobiscr 

**Attachments**

**Comment by a-thaler** [comment]
Not relevant anymore as the whole setup will be covered by the reconcilation logic which will be documented anyway
