### ISSUE TITLE
New installation: Flag to toggle atomic upgrades

### ISSUE THREAD

**Issue by clebs** [kyma-project/cli#755]
**Description**

In a normal upgrade, if components can't be upgraded, the installation library will rollback. This can be problematic in non-productive clusters if we wish to debug the issues.

Add a flag to the CLI to toggle upgrade rollbacks:
`kyma alpha deploy --atomic=false` -> This will disable rollbacks when upgrading.

**Reasons**

Allow better debugging capabilities, rollbacks need to be disabled on demand.

**Attachments**
Depends on the support for the flag in Hydroform: https://github.com/kyma-incubator/hydroform/issues/195

**Comment by tobiscr** [comment]
The PR for CLI requires the changes in PR https://github.com/kyma-incubator/hydroform/pull/198 as we have to update the Hydroform-API before this PR can be merged.

**Comment by a-thaler** [comment]
Flag is not effective and even worse by default no rollback seem to happen, re-opened

**Comment by tobiscr** [comment]
Counter part on hydroform side is https://github.com/kyma-incubator/hydroform/pull/209

**Comment by tobiscr** [comment]
Please be aware to use this notation to disable the atomic flag: `--atomic=false` 

Tested it also with `--atomic false` and the atomic-flag was still set to `true`.
