### ISSUE TITLE
New Installation: Move value resolution to hydroform

### ISSUE THREAD

**Issue by clebs** [kyma-project/cli#756]
**Description**

Currently the CLI resolves many global values on its own before sending them to the install API.
This poses several limitations since the CLI can not resolve everything beforehand (e.g. which domain to use on an upgrading or gardener cluster).

Remove all global values defaults and resolution from the CLI and move them to Hydroform. There, overrides interceptors shall be used to resolve values with as much information from the environment as possible.

**Reasons**
Moving value resolution down the chain will allow to select the correct value for each property with much more information and accuracy.

**Comment by tobiscr** [comment]
Please see https://github.com/kyma-incubator/hydroform/pull/197 which calls an interceptor if an override key is missing.
