### ISSUE TITLE
kyma provision aks fails with "remove ... terraform.tfstate: no such file or directory" error on Mac OSX and Linux

### ISSUE THREAD

**Issue by sblessing** [kyma-project/cli#815]
**Description**

When provisioning a kubernetes service with kyma-cli using the following command

` kyma provision aks -c aks_credentials.json -n $CLUSTER_NAME -p $RS_GROUP -l $REGION `

the provisioning attempt fails with

```
X Provisioning AKS cluster

Error: All attempts fail:
#1: unable to provision azure cluster: remove /Users/.../.kyma/clusters/azure/.../kyma/terraform.tfstate: no such file or directory
```

`env` (CLUSTER_NAME, RS_GROUP and REGION) are set correctly.

**Expected result**

Successful provisioning of kubernetes aks service.

**Actual result**

Error message `terraform.tfstate: no such file or directory`. Provisioning is aborted.

**Steps to reproduce**

kyma-cli 1.20.0, standard installation guide "AKS with own domain", https://kyma-project.io/docs/#installation-install-kyma-with-your-own-domain.

**Troubleshooting**

Retried the installation on two different Mac OSX Versions, both with kyma-cli 1.20.0.

My release information is:

```
kyma version

Kyma CLI version: 1.20.0
```

```
kubectl version 

Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-dirty", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"dirty", BuildDate:"2021-03-15T10:03:32Z", GoVersion:"go1.16.2", Compiler:"gc", Platform:"darwin/amd64"}
```

Provisioning an AKS on Windows does **not work** for **other reasons**: https://github.com/kyma-project/cli/issues/619.

Provisioning an AKS on Ubuntu 20.04.1 LTS does **not work** for the **same reason**:

```
uname -a
Linux 5.4.0-67-generic #75-Ubuntu SMP Fri Feb 19 18:03:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```

```
kyma provision aks -c aks_credentials.json -n $CLUSTER_NAME -p $RS_GROUP -l $REGION

X Provisioning AKS cluster
Error: unable to provision azure cluster: remove /home/dns/.kyma/clusters/azure/kubernetes-dev-rg/kyma/terraform.tfstate: no such file or directory
```

Touching the terraform.tfstate file at the specified location above doesn't change the behavior. In fact, a manually touched terraform.tfstate is removed after running the command above.

This pretty much sounds like a race condition in some go pipeline.

Maybe this issue is related to something similar raised here: https://github.com/kyma-incubator/hydroform/issues/61.

**Comment by clebs** [comment]
Hi @sblessing,
thanks for reporting this issue. Unfortunately, I was not able t reproduce it on Kyma CLI `1.20.0` or `1.19.0`; I was able to provision a cluster on AKS with the following command:
`kyma provision aks -n ${CLUSTER_NAME} -p ${RS_GROUP} -c ${JSON_CRED_FILE}`

To be able t help you further, could you please run the provisioning again with the `--verbose` flag please? It might give us more insight on what is going wrong.

Thank you!

**Comment by sblessing** [comment]
Hi @clebs,

unfortunately, the verbose mode those nothing else than printing the error message three times.

```
X Provisioning AKS cluster
Error: All attempts fail:
#1: unable to provision azure cluster: remove /Users/sebastian/.kyma/clusters/azure/kubernetes-dev-rg/kyma/terraform.tfstate: no such file or directory
#2: unable to provision azure cluster: remove /Users/sebastian/.kyma/clusters/azure/kubernetes-dev-rg/kyma/terraform.tfstate: no such file or directory
#3: unable to provision azure cluster: remove /Users/sebastian/.kyma/clusters/azure/kubernetes-dev-rg/kyma/terraform.tfstate: no such file or directory
```

**Comment by clebs** [comment]
Hi @sblessing,

thanks for the information.  wanted to see if something different was happening before this error, but it seems not.

This is quite strange, the CLI provisioning should not be deleting any files from your terraform state.

I am also running on Go 1.16, so that is probably not it...

Could you please check the content of the following folder?:
`/Users/sebastian/.kyma/clusters/azure/kubernetes-dev-rg/kyma`

It should contain the following:
```
drwxr-xr-x .terraform
-rw-r--r-- README.md
-rw-r--r-- aks.tf
-rw-r--r-- main.tf
-rw-r--r-- outputs.tf
-rw-r--r-- terraform.tfstate
-rw-r--r-- terraform.tfstate.backup
-rwx------ terraform.tfvars
drwxr-xr-x test
-rw-r--r-- variables.tf
```

If it is not the case, please try deleting the folder `/Users/sebastian/.kyma/clusters/azure/kubernetes-dev-rg/kyma` and see if starting over from scratch helps.

**Comment by sblessing** [comment]
Hi @clebs

i had noticed beforehand, that the terraform.tfstate does not exist in my case.

```
drwx------  10 sebastian  staff   320 24 Mär 11:19 .
drwx------   4 sebastian  staff   128 22 Mär 12:46 ..
drwxr-xr-x   2 sebastian  staff    64 22 Mär 11:26 .terraform
-rw-r--r--   1 sebastian  staff  4445 22 Mär 11:26 README.md
-rw-r--r--   1 sebastian  staff  2174 22 Mär 11:26 aks.tf
-rw-r--r--   1 sebastian  staff   646 22 Mär 11:26 main.tf
-rw-r--r--   1 sebastian  staff  1525 22 Mär 11:26 outputs.tf
-rwx------   1 sebastian  staff   399 24 Mär 11:19 terraform.tfvars
drwxr-xr-x   4 sebastian  staff   128 22 Mär 11:26 test
-rw-r--r--   1 sebastian  staff  2476 22 Mär 11:26 variables.tf
```

Also, deleting the folder and starting over from scratch produces the name error:

```
rm -rf /Users/sebastian/.kyma/clusters/azure/kubernetes-dev-rg/kyma/ && kyma provision aks -n $CLUSTER_NAME -p $RS_GROUP -c aks_credentials.json 

X Provisioning AKS cluster
Error: unable to provision azure cluster: remove /Users/sebastian/.kyma/clusters/azure/kubernetes-dev-rg/kyma/terraform.tfstate: no such file or directory
```

**Comment by clebs** [comment]
That `terraform.tfstate` file on the root of your `.kyma` folder should not cause any issues as far as I know.
This case is quite interesting... I am afraid I need to investigate deeper.

We will come back to you when I have new findings.

**Comment by clebs** [comment]
Added a new task on our backlog to improve the terraform debugging under the hood in Hydroform: #882 
This will allow us t assist further on this issue which we unfortunately can't reproduce.

**Comment by clebs** [comment]
Hi @sblessing,
unfrtunately this information does not help us further...

Good news is that we have added stronger debugging capabilities to the Kyma CLI when provisioning (see #882 for details).
When the CLI `1.23.0` is released next month this feature will be included, which will allow you to get a lot more information on the provisioning process using the `--verbose` flag.

**Comment by pbochynski** [comment]
Closed due to inactivity.
