### ISSUE TITLE
New Installation: Allowing single component deployment

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/cli#826]
**Description**

To improv the development speed it has to be possible to install of one or more defined components deployment. 

The CLI has to support an option to provide a list of components (as arguments, e.g. `--component abc --component xyz@namespace`).

**Reasons**

Improve development speed and offer a more flexible way how to install custom Kyma components beside using a file (component-list).

**Attachments**

**Comment by a-thaler** [comment]
Adjust examples at https://kyma-project.io/docs/main/cli/overview/#details-kyma-cli-alpha-command-usage-examples please
