### ISSUE TITLE
New Installation: Single component deployment via sub-command

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/cli#827]
**Description**

To improv the development speed it has to be possible to install of one or more defined components deployment. 

A sub-command (e.g. `kyma alpha deploy component`, `kyma alpha delete component`) has to be added to offer the user a way to install components directly.

**Reasons**

Improve development speed and offer a more flexible way how to install custom Kyma components beside using a file (component-list).

**Attachments**

**Comment by shorim** [comment]
`component` sub-command is not relevant at the moment. So, this issue will be closed for now,
