### ISSUE TITLE
Allow doing patch releases from CLI without Kyma release

### ISSUE THREAD

**Issue by suleymanakbas91** [kyma-project/cli#836]
**Description**

Right now Kyma CLI releases are bound to Kyma releases because of the default Kyma version set in the [Homebrew formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/kyma-cli.rb#L21). That's why we cannot do hot fixes on CLI and release a new patch version if there is no new version being released from Kyma. We should find another way to set the default Kyma version so that we can release Kyma CLI patches without releasing Kyma.

**Acceptance Criteria**
- Allow releasing Kyma CLI patches without releasing Kyma.

**Comment by clebs** [comment]
Reopening issue since CLI release guidelines have not been updated.
