### ISSUE TITLE
Allow Branch-Names as source for Kyma installation, instead of just 'master'

### ISSUE THREAD

**Issue by JeremyHarisch** [kyma-project/cli#837]
**Description**
Using `kyma install -s <branch-name>` to install kyma from a specific branch.

**Expected result**
Kyma is getting installed using the specified branch as source.

**Actual result**
Only the master branch can be used. And regarding the new naming conventions, `master` is now called `main` --> Main branch cannot be used, because of the naming.

**Comment by JeremyHarisch** [comment]
Issue was moved to hydroform (https://github.com/kyma-incubator/hydroform/issues/238)

**Comment by a-thaler** [comment]
In-line docu is not updated yet

**Comment by JeremyHarisch** [comment]
This only works for alpha commands until now. Needs to be added for non-alpha commands as well.

**Comment by JeremyHarisch** [comment]
This issue is closed with the following findings:
* It is possible to install kyma from a specific branch using the `alpha deploy` command. This was integrated with this [PR](https://github.com/kyma-project/hydroform/pull/239) Example: `kyma alpha deploy source=main`
* Installing kyma from a specific branch using the non-alpha install command (`kyma install`) will not be implemented due to the following reasons:
  * `install` uses kyma artifacts to install kyma
  * artifacts are only available for PRs and released kyma versions, not for every branch
  * We could implement it in a way that we fetch the wanted git-branch and create some custom artifacts, but this would take too much effort since this command will be deprecated soon

Thus, allowing branch names as a source to install kyma from, will only be supported with the alpha commands.
