### ISSUE TITLE
Adapt installation/utils Test after master/main migration

### ISSUE THREAD

**Issue by JeremyHarisch** [kyma-project/cli#840]
**Description**
Regarding the [master-to-main migration ](https://github.com/kyma-project/cli/pull/841)the following test need to be adopted:
- [LoadInstallationFiles](https://github.com/kyma-project/cli/blob/main/pkg/installation/utils_test.go#L19)

 Due to the reason we do not have `main`-branch-artifacts until the migration is done, we need to wait until the first version is built with the new main branch and then provide those artifacts to the test.

**Comment by JeremyHarisch** [comment]
@clebs is this issue still to-be-done or has it been already fixed last week?

**Comment by clebs** [comment]
This issue can be closed since it was solved in the migration PR.
