### ISSUE TITLE
Add kiali and tracing component to new alpha deploy flow

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/cli#850]
**Description**
Kiali and tracing component comes with a keycloak-proxy to have authentication in place for exposure of the UI. As with Kyma 2.0 there is no pre-integrated authentication on top of k8s rbac, the proxy was not starting up anymore with the new kyma alpha deploy command.

With https://github.com/kyma-project/kyma/pull/10813 the proxies are made configurable so please re-enable the components for the new kyma deploy flow.

AC:
- both components are listed in the default components.yaml
- both components are getting installed with "kyma alpha deploy"
- pipelines are green

**Reasons**

**Attachments**

Relates to https://github.com/kyma-project/hydroform/pull/254

**Comment by JeremyHarisch** [comment]
Not all PRs are merged until now

**Comment by JeremyHarisch** [comment]
Not all PRs are merged until now
