### ISSUE TITLE
New Installation: workspace directory name and location should be changed

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/cli#854]
**Description**

The default location of the `workspace` directory is the current working directly. This can cause unnecessary permission issues. Also the name `workspace` is not the best choice, as it  is a common name and sometimes used by users to store their work related data.

The workspace directory should be 

1. located in a place where no write-permissions are expected (e.g. `$HOME`)
2. be place either in a sub-directory (e.g.  `$HOME/.kyma-cli/ws` ) or using a name which has a low risk to collide with existing directories (e.g. `kyma-cli-ws`)

**Reasons**

Users were complaining the the workspace folder location is colliding with their existing folder structure.

**Attachments**

**Comment by clebs** [comment]
Hi @tobiscr,
this is a good improvement. The CLI already has a `~/.kyma` folder that we can use.
See:
https://github.com/kyma-project/cli/blob/8234ebcf09634b8df687801530689bb85f701c4e/internal/files/files.go#L12
