### ISSUE TITLE
Read user provided defaults while executing CLI commands

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/cli#871]
**Description**

Implement a mechanism allowing users to define custom default values in the file and have them applied when running CLI commands options (i.e `--runtime`, `--namespace`)

As a CLI user I would like to provide an input file for default values when managing functions via CLI.
I.e  as NodeJS developer developing function within my test namespace I dont want to repeat myself in the CLI commands

**Reasons**
It is a common practice and nice comfort level for CLI users to provide custom defaults (inspired by tools like  `kubectl`, `gcloud` )

**Attachments**

**Comment by Disper** [comment]
We might new to discuss it further with @m00g3n and @kwiatekus.
