### ISSUE TITLE
Installation issue with Hydroform in prow jobs

### ISSUE THREAD

**Issue by sayanh** [kyma-project/cli#877]
**Description**

Installation fails quite frequently with Hydroform in prow jobs.
Samples:
https://storage.googleapis.com/kyma-prow-logs/logs/kyma-alpha-integration-evaluation-gardener-azure/1385233419918643200/build-log.txt
https://storage.googleapis.com/kyma-prow-logs/logs/kyma-alpha-integration-evaluation-gardener-azure/1385233419918643200/build-log.txt

**Comment by a-thaler** [comment]
Already fixed
