### ISSUE TITLE
Integrate terraform debugging

### ISSUE THREAD

**Issue by clebs** [kyma-project/cli#882]
**Description**

Adapt the CLI to the terraform debug option to be added in https://github.com/kyma-project/hydroform/issues/252.
Either we can reuse the verbose flag or have a separate `debug` flag for it.

**Reasons**
Improve debugging and troubleshooting on cluster provisioning.
For example, we have not enough information to assist on this issue #815

**Attachments**
Has to be done after: https://github.com/kyma-project/hydroform/issues/252

**Comment by elchead** [comment]
The --verbose flag can be used to output terraform logs
