### ISSUE TITLE
Convenient installation configuration

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/cli#89]
**Description**
The CLI allows to install kyma on minikube with two easy commands. By doing that, it supports very technical options to customize the installation by specifying custom config.yaml and configuration overrides.
There are two things very typical customizations you require quite often:
- enrich the list of modules to install (I want more modules like monitoring on top of standard lite installation)
- customize settings per module (like custom admin password)
That two scenarios should be achievable in a very easy way, preferably in a persistent manner so that you can re-use the setting for the next installation again.

As inspiration take a look at the kyma installation scripts, there is a hidden feature by specifying a components.env file (https://github.com/kyma-project/kyma/issues/3995)

**Reasons**
The CLI should abstract any technical details and should assure that installing kyma will be an easy task keeping full flexibility.

**Comment by iancrowther** [comment]
@a-thaler it would be great if the -p flag was carried through also so you can name your minikube instances.

**Comment by suleymanakbas91** [comment]
I believe this is done with https://github.com/kyma-project/cli/pull/474.
