### ISSUE TITLE
Explicits overrides specific for new installation

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/cli#892]
**Description**
The new installer is based on the kyma 2 sources already and with that has a specific component setup. That setup requires some specific settings at the moment, for example disabling the kcproxy for tracing.

At the moment these settings are hardcoded as interceptors in the new installer lib.
Goal: Make them explicit as dedicated values.yaml file in the kyma repo which will be downloaded automatically by the CLI for now. 

Acceptance:
- Have a place where to define all kyma 2 specific settings
- That settings will be applied always when using the new installer command
- interceptors which exist only for that purpose are removed
- 

**Reasons**

**Attachments**

**Comment by elchead** [comment]
Borja released a CLI version with these changes
