### ISSUE TITLE
Implement function versioning functionality

### ISSUE THREAD

**Issue by pPrecel** [kyma-project/cli#953]
**Description**

Implement functionality that helps with versioning functions and (for example) ask users before `kyma apply function` always when the local workspace is out of sync (when the function on the cluster is after a few changes). 

This system should help users with working on functions in groups and with checking on which function version they are working on.

**Reasons**

Now users working in groups on the one function should `sync` the local workspace before applying any function to the cluster. The `sync` command will override all changes in the workspace are which is an impediment to daily development. Users should get good tooling to develop functions fast and safely.

**Comment by kwiatekus** [comment]
True function versioning should be done via git.
