### ISSUE TITLE
Provision AKS uses deprecated statement

### ISSUE THREAD

**Issue by lechnerc77** [kyma-project/cli#958]
**Description**

Executing the Kyma CLI to provision an AKS cluster leads to a deprecation warning.

The command is:
`kyma provision aks -c ./aksprincipal.json -n $CLUSTER_NAME -p $RS_GROUP -l $REGION`

The corresponding warning is:
` Warning: "agent_pool_profile": [DEPRECATED] This has been replaced by `default_node_pool` and will be removed in version 2.0 of the AzureRM Provider`.

This is caused by the underlying terraform module for [AKS](https://github.com/kyma-incubator/terraform-modules/blob/d196ee4ffce33099318fe6b1994282c99883bada/azurerm_kubernetes_cluster/aks.tf)

**Expected result**

No deprecation warning is displayed.

**Actual result**

A deprecation warning is shown.

**Steps to reproduce**

Follow the installation instructions for Kyma on a cluster (<https://kyma-project.io/docs/#installation-install-kyma-on-a-cluster>)  for AKS.  

**Troubleshooting**

/

**Comment by pbochynski** [comment]
We are in the process of removing provision commands from Kyma CLI. In this case azure cli would be better choice. I mean we are not going to invest in this area any more as Kyma can be installed on any k8s cluster.
