### ISSUE TITLE
Decouple kyma version for kyma install command

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/cli#973]
**Description**
With the kyma 2 release, the new command to install kyma on a cluster will be the "kyma deploy" command. The old "kyma install will still exist for a while and must be based on the release branch version for kyma 1.

Goal: Have the default kyma version to install with the "kyma install" command separated from the version used in the "kyma deploy" command.

- "kyma install" will kyma in version 1.24.x
- "kyma deploy" will install kyma with latest release

**Reasons**

**Attachments**

**Comment by shorim** [comment]
Re-opening as we still need to wait until the PR for the modification of the CLI release guidlines is merged: kyma-project/community#589

**Comment by shorim** [comment]
Re-opening as we still need to wait until the PR for the modification of the CLI release guidlines is merged: kyma-project/community#589

**Comment by a-thaler** [comment]
Not all is merged, re-opening
